<?php
namespace Aio\Services;
use Aio\DB;use PDO;
final class ExactPageData {
  private static function money($n):string{return 'PKR '.number_format((float)$n,0);}
  private static function count(PDO $p,string $sql,array $a=[]):int{$q=$p->prepare($sql);$q->execute($a);return(int)$q->fetchColumn();}
  private static function sum(PDO $p,string $sql,array $a=[]):float{$q=$p->prepare($sql);$q->execute($a);return(float)$q->fetchColumn();}
  private static function mode(string $m):string{return ['DINE_IN'=>'Dine In','TAKEAWAY'=>'Takeaway','DELIVERY'=>'Home Delivery'][$m]??$m;}
  public static function moduleData(string $page):?array{
    $p=DB::pdo();$rows=[];$stats=[];
    if($page==='customers.html'){
      $q=$p->prepare("SELECT c.full_name,c.phone,c.customer_type,c.created_at,(SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id) orders,(SELECT COALESCE(SUM(o.grand_total),0) FROM orders o WHERE o.customer_id=c.id AND o.order_status='CLOSED') spend,(SELECT COALESCE(points_balance,0) FROM loyalty_accounts l WHERE l.customer_id=c.id LIMIT 1) points,(SELECT MAX(o.closed_at) FROM orders o WHERE o.customer_id=c.id AND o.order_status='CLOSED') last_order FROM customers c WHERE c.tenant_id=? AND c.status='ACTIVE' ORDER BY c.created_at DESC LIMIT 100");$q->execute([tenant_id()]);
      foreach($q->fetchAll() as $x)$rows[]=[$x['full_name'],$x['phone']?:'—',$x['orders'],self::money($x['spend']),number_format((float)$x['points'],0),$x['last_order']?date('d M Y',strtotime($x['last_order'])):'—',ucfirst(strtolower($x['customer_type']))];
      $stats=[count($rows),self::count($p,"SELECT COUNT(*) FROM customers WHERE tenant_id=? AND customer_type='VIP' AND status='ACTIVE'",[tenant_id()]),self::count($p,"SELECT COUNT(*) FROM customers WHERE tenant_id=? AND DATE(created_at)=CURDATE()",[tenant_id()]),self::money(self::sum($p,"SELECT COALESCE(SUM(grand_total),0) FROM orders WHERE site_id=? AND business_date=CURDATE() AND order_status='CLOSED'",[site_id()]))];
    }elseif($page==='orders_management.html'){
      $q=$p->prepare("SELECT o.bill_no,o.service_mode,COALESCE(dt.display_name,c.full_name,'Walk-in') target,u.full_name waiter,o.grand_total,o.order_status,o.opened_at,(SELECT COUNT(*) FROM kitchen_tickets k WHERE k.order_id=o.id AND k.ticket_status IN ('NEW','PREPARING')) kitchen FROM orders o LEFT JOIN dining_tables dt ON dt.id=o.table_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN users u ON u.id=o.waiter_user_id WHERE o.site_id=? AND o.order_status<>'CLOSED' ORDER BY o.opened_at DESC LIMIT 100");$q->execute([site_id()]);
      foreach($q->fetchAll() as $x)$rows[]=[$x['bill_no'],self::mode($x['service_mode']),$x['target'],$x['waiter']?:'—',self::money($x['grand_total']),((int)$x['kitchen']?'In Kitchen':$x['order_status']),floor((time()-strtotime($x['opened_at']))/60).'m'];
      $stats=[count($rows),self::count($p,"SELECT COUNT(*) FROM orders WHERE site_id=? AND hold_status=1 AND order_status<>'CLOSED'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status IN ('NEW','PREPARING')",[site_id()]),self::count($p,"SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status='READY'",[site_id()])];
    }elseif($page==='suppliers.html'){
      $q=$p->prepare("SELECT s.id,s.name,s.phone,(SELECT COUNT(*) FROM supplier_items si WHERE si.supplier_id=s.id) items,(SELECT COALESCE(SUM(gr.total_amount),0) FROM goods_receipts gr WHERE gr.supplier_id=s.id AND MONTH(gr.received_at)=MONTH(CURDATE()) AND YEAR(gr.received_at)=YEAR(CURDATE())) mtd,(SELECT COALESCE(MAX(gr.received_at),'') FROM goods_receipts gr WHERE gr.supplier_id=s.id) last_purchase FROM suppliers s WHERE s.tenant_id=? AND s.status='ACTIVE' ORDER BY s.name");$q->execute([tenant_id()]);
      foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['phone']?:'—',$x['items'],self::money($x['mtd']),'PKR 0',$x['last_purchase']?date('d M Y',strtotime($x['last_purchase'])):'—'];
      $stats=[count($rows),'PKR 0',self::money(array_sum(array_map(fn($r)=>(float)str_replace([',','PKR '],'',$r[3]),$rows))),'PKR 0'];
    }elseif($page==='reservations.html'){
      $q=$p->prepare("SELECT DATE_FORMAT(r.reservation_at,'%h:%i %p') tm,r.guest_name,r.guest_count,COALESCE(dt.display_name,'—') table_name,r.deposit_amount,r.status FROM reservations r LEFT JOIN reservation_tables rt ON rt.reservation_id=r.id LEFT JOIN dining_tables dt ON dt.id=rt.table_id WHERE r.site_id=? AND DATE(r.reservation_at)>=CURDATE() ORDER BY r.reservation_at LIMIT 100");$q->execute([site_id()]);
      foreach($q->fetchAll() as $x)$rows[]=[$x['tm'],$x['guest_name'],$x['guest_count'],$x['table_name'],self::money($x['deposit_amount']),$x['status']];
      $stats=[self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND DATE(reservation_at)=CURDATE()",[site_id()]),self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND reservation_at BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL 2 HOUR)",[site_id()]),self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND status='WAITLIST'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND DATE(reservation_at)=CURDATE() AND status='NO_SHOW'",[site_id()])];
    }elseif($page==='delivery.html'){
      $q=$p->prepare("SELECT o.bill_no,COALESCE(c.full_name,'Walk-in') customer,d.delivery_area,o.grand_total,COALESCE(pm.name,'COD') payment,COALESCE(r.name,'Not Assigned') rider,d.delivery_status FROM delivery_orders d JOIN orders o ON o.id=d.order_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN payments py ON py.order_id=o.id LEFT JOIN payment_methods pm ON pm.id=py.payment_method_id LEFT JOIN riders r ON r.id=d.rider_id WHERE d.site_id=? ORDER BY o.opened_at DESC LIMIT 100");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['bill_no'],$x['customer'],$x['delivery_area']?:'—',self::money($x['grand_total']),$x['payment'],$x['rider'],$x['delivery_status']];
      $stats=[self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND delivery_status IN ('WAITING','READY')",[site_id()]),self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND delivery_status IN ('PICKED_UP','ON_THE_WAY')",[site_id()]),self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND DATE(delivered_at)=CURDATE()",[site_id()]),self::count($p,"SELECT COUNT(*) FROM riders WHERE site_id=? AND status='AVAILABLE'",[site_id()])];
    }elseif($page==='rider_management.html'){
      $q=$p->prepare("SELECT r.id,r.name,r.phone,r.status,r.cash_held,(SELECT o.bill_no FROM delivery_orders d JOIN orders o ON o.id=d.order_id WHERE d.rider_id=r.id AND d.delivery_status NOT IN ('DELIVERED','CANCELLED') ORDER BY o.opened_at DESC LIMIT 1) current_order FROM riders r WHERE r.site_id=? ORDER BY r.name");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['phone']?:'—',$x['current_order']?:'—',self::money($x['cash_held']),$x['status']];$stats=[count($rows),self::money(self::sum($p,"SELECT COALESCE(SUM(cash_held),0) FROM riders WHERE site_id=?",[site_id()])),self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND DATE(delivered_at)=CURDATE()",[site_id()]),self::count($p,"SELECT COUNT(*) FROM riders WHERE site_id=? AND status='AVAILABLE'",[site_id()])];
    }elseif($page==='expenses.html'){
      $q=$p->prepare("SELECT e.expense_no,ec.name category,e.amount,COALESCE(u.full_name,'—') user_name,e.status FROM expenses e JOIN expense_categories ec ON ec.id=e.category_id LEFT JOIN users u ON u.id=e.created_by_user_id WHERE e.site_id=? ORDER BY e.expense_date DESC,e.created_at DESC LIMIT 100");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['expense_no'],$x['category'],self::money($x['amount']),$x['user_name'],$x['status']];$stats=[self::money(self::sum($p,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE site_id=? AND expense_date=CURDATE()",[site_id()])),self::money(self::sum($p,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE site_id=? AND MONTH(expense_date)=MONTH(CURDATE()) AND YEAR(expense_date)=YEAR(CURDATE())",[site_id()])),self::count($p,"SELECT COUNT(*) FROM expenses WHERE site_id=? AND status='PENDING'",[site_id()]),'—'];
    }elseif($page==='fbr.html'){
      $q=$p->prepare("SELECT o.bill_no,COALESCE(f.provider_invoice_no,'Pending') fbr,f.status,IF(f.status='PENDING','Retry / Queue','View') action FROM fiscal_invoices f JOIN orders o ON o.id=f.order_id WHERE f.site_id=? ORDER BY COALESCE(f.submitted_at,o.closed_at) DESC LIMIT 100");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['bill_no'],$x['fbr'],$x['status'],$x['action']];$stats=['Configured',self::count($p,"SELECT COUNT(*) FROM fiscal_invoices WHERE site_id=? AND DATE(COALESCE(submitted_at,NOW()))=CURDATE()",[site_id()]),'—',self::count($p,"SELECT COUNT(*) FROM fiscal_invoices WHERE site_id=? AND status IN ('FAILED','PENDING')",[site_id()])];
    }elseif($page==='printer_devices.html'){
      $q=$p->prepare("SELECT name,CONCAT(printer_type,' / ',COALESCE(station_code,'—')) typ,CONCAT(COALESCE(ip_address,''),IF(port_no IS NULL,'',CONCAT(':',port_no))) addr,COALESCE(station_code,'—') cat,IF(is_active=1,'Online','Disabled') status FROM printers WHERE site_id=? ORDER BY name");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['typ'],$x['addr'],$x['cat'],$x['status']];$stats=[self::count($p,"SELECT COUNT(*) FROM printers WHERE site_id=? AND printer_type='RECEIPT' AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM printers WHERE site_id=? AND printer_type='KITCHEN' AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM devices WHERE site_id=? AND device_type='KDS' AND status='ACTIVE'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM devices WHERE site_id=? AND status='ACTIVE'",[site_id()])];
    }elseif($page==='multi_branch.html'){
      $q=$p->prepare("SELECT s.id,s.name,s.status,(SELECT COALESCE(SUM(o.grand_total),0) FROM orders o WHERE o.site_id=s.id AND o.business_date=CURDATE() AND o.order_status='CLOSED') sales,(SELECT COUNT(*) FROM orders o WHERE o.site_id=s.id AND o.business_date=CURDATE()) orders,(SELECT COALESCE(SUM(sb.qty_on_hand*sb.avg_cost),0) FROM stock_balances sb WHERE sb.site_id=s.id) stock,(SELECT COUNT(*) FROM cashier_shifts cs WHERE cs.site_id=s.id AND cs.status='OPEN') open_shift FROM sites s WHERE s.tenant_id=? ORDER BY s.name");$q->execute([tenant_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['name'],self::money($x['sales']),$x['orders'],self::money($x['stock']),((int)$x['open_shift']?'Open':'Closed'),$x['status']];$stats=[count($rows),self::money(self::sum($p,"SELECT COALESCE(SUM(grand_total),0) FROM orders WHERE tenant_id=? AND business_date=CURDATE() AND order_status='CLOSED'",[tenant_id()])),self::count($p,"SELECT COUNT(*) FROM cashier_shifts WHERE tenant_id=? AND status='OPEN'",[tenant_id()]),self::count($p,"SELECT COUNT(*) FROM sites WHERE tenant_id=? AND status='ACTIVE'",[tenant_id()])];
    }elseif($page==='stock_transfer.html'){
      $q=$p->prepare("SELECT t.transfer_no,fs.name fr,ts.name too,(SELECT COUNT(*) FROM stock_transfer_items i WHERE i.transfer_id=t.id) items,(SELECT COALESCE(SUM(i.requested_qty*ii.avg_cost_per_stock_unit),0) FROM stock_transfer_items i JOIN inventory_items ii ON ii.id=i.inventory_item_id WHERE i.transfer_id=t.id) val,t.status FROM stock_transfers t JOIN sites fs ON fs.id=t.from_site_id JOIN sites ts ON ts.id=t.to_site_id WHERE t.tenant_id=? ORDER BY t.created_at DESC LIMIT 100");$q->execute([tenant_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['transfer_no'],$x['fr'],$x['too'],$x['items'],self::money($x['val']),$x['status']];$stats=[self::count($p,"SELECT COUNT(*) FROM stock_transfers WHERE tenant_id=? AND status LIKE 'PENDING%'",[tenant_id()]),self::count($p,"SELECT COUNT(*) FROM stock_transfers WHERE tenant_id=? AND status='IN_TRANSIT'",[tenant_id()]),self::count($p,"SELECT COUNT(*) FROM stock_transfers WHERE tenant_id=? AND DATE(received_at)=CURDATE()",[tenant_id()]),0];
    }elseif($page==='void_refund.html'){
      $q=$p->prepare("SELECT DATE_FORMAT(v.created_at,'%h:%i %p') tm,o.bill_no,oi.item_name_snapshot,v.void_qty,v.reason_code,COALESCE(ru.full_name,'—') req,COALESCE(au.full_name,'Pending') app FROM order_item_voids v JOIN orders o ON o.id=v.order_id JOIN order_items oi ON oi.id=v.order_item_id LEFT JOIN users ru ON ru.id=v.requested_by_user_id LEFT JOIN users au ON au.id=v.approved_by_user_id WHERE v.site_id=? ORDER BY v.created_at DESC LIMIT 100");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['tm'],$x['bill_no'],'Item Void · '.$x['item_name_snapshot'],$x['void_qty'],$x['reason_code'],$x['req'],$x['app']];$stats=[count($rows),self::count($p,"SELECT COUNT(*) FROM order_item_voids WHERE site_id=? AND approval_status='APPROVED'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM refunds WHERE site_id=? AND DATE(created_at)=CURDATE()",[site_id()]),self::count($p,"SELECT COUNT(*) FROM refunds WHERE site_id=? AND status='PENDING'",[site_id()])];
    }elseif($page==='tables_floors.html'){
      $q=$p->prepare("SELECT dt.display_name,COALESCE(f.name,'—') area,dt.seats,dt.status,COALESCE(u.full_name,'—') waiter,COALESCE(o.bill_no,'—') bill FROM dining_tables dt LEFT JOIN floors f ON f.id=dt.floor_id LEFT JOIN orders o ON o.table_id=dt.id AND o.order_status<>'CLOSED' LEFT JOIN users u ON u.id=o.waiter_user_id WHERE dt.site_id=? AND dt.is_active=1 ORDER BY f.sort_order,dt.display_name");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['display_name'],$x['area'],$x['seats'],$x['status'],$x['waiter'],$x['bill']];$stats=[self::count($p,"SELECT COUNT(*) FROM dining_tables WHERE site_id=? AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM dining_tables WHERE site_id=? AND status='AVAILABLE' AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM dining_tables WHERE site_id=? AND status<>'AVAILABLE' AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM floors WHERE site_id=? AND is_active=1",[site_id()])];
    }elseif($page==='shift_management.html'){
      $q=$p->prepare("SELECT pm.name,SUM(py.amount) system_total,SUM(py.amount) counted,0 variance FROM payments py JOIN payment_methods pm ON pm.id=py.payment_method_id JOIN cashier_shifts cs ON cs.id=py.shift_id WHERE cs.site_id=? AND cs.status='OPEN' GROUP BY pm.id,pm.name ORDER BY pm.name");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['name'],self::money($x['system_total']),self::money($x['counted']),self::money($x['variance'])];$stats=[self::count($p,"SELECT COUNT(*) FROM cashier_shifts WHERE site_id=? AND status='OPEN'",[site_id()]),self::money(self::sum($p,"SELECT COALESCE(SUM(grand_total),0) FROM orders WHERE site_id=? AND business_date=CURDATE() AND order_status='CLOSED'",[site_id()])),self::money(self::sum($p,"SELECT COALESCE(SUM(opening_cash),0) FROM cashier_shifts WHERE site_id=? AND status='OPEN'",[site_id()])),self::count($p,"SELECT COUNT(*) FROM orders WHERE site_id=? AND business_date=CURDATE() AND order_status='CLOSED'",[site_id()])];
    }elseif($page==='menu_management.html'){
      $q=$p->prepare("SELECT mi.name,CONCAT('Item / ',mc.name) typ,CONCAT(COALESCE(p.name,'No Printer'),' / ',?,FORMAT(mi.base_price,0)) display,IF(mi.is_active=1,'Active','Disabled') status FROM menu_items mi JOIN menu_categories mc ON mc.id=mi.category_id LEFT JOIN menu_category_printer_routes r ON r.category_id=mc.id AND r.is_primary=1 AND r.is_active=1 LEFT JOIN printers p ON p.id=r.printer_id WHERE mi.site_id=? AND mi.deleted_at IS NULL ORDER BY mc.sort_order,mi.name LIMIT 150");$q->execute(['PKR ',site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['typ'],$x['display'],$x['status']];$stats=[self::count($p,"SELECT COUNT(*) FROM menu_categories WHERE site_id=? AND deleted_at IS NULL",[site_id()]),self::count($p,"SELECT COUNT(*) FROM menu_items WHERE site_id=? AND deleted_at IS NULL",[site_id()]),self::count($p,"SELECT COUNT(*) FROM menu_items WHERE site_id=? AND is_online=1 AND deleted_at IS NULL",[site_id()]),self::count($p,"SELECT COUNT(*) FROM menu_category_printer_routes WHERE site_id=? AND is_active=1",[site_id()])];
    }elseif($page==='stock_count.html'){
      $q=$p->prepare("SELECT ii.name,sci.system_qty,COALESCE(sci.physical_qty,0) physical_qty,COALESCE(sci.variance_qty,0) variance_qty,COALESCE(sci.variance_value,0) variance_value,COALESCE(sci.reason_code,'—') reason_code FROM stock_count_items sci JOIN stock_count_sessions scs ON scs.id=sci.count_session_id JOIN inventory_items ii ON ii.id=sci.inventory_item_id WHERE scs.site_id=? ORDER BY scs.started_at DESC,ii.name LIMIT 150");$q->execute([site_id()]);foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['system_qty'],$x['physical_qty'],$x['variance_qty'],self::money($x['variance_value']),$x['reason_code']];
      $stats=[self::count($p,"SELECT COUNT(*) FROM stock_count_sessions WHERE site_id=? AND status='OPEN'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM inventory_items WHERE site_id=? AND deleted_at IS NULL",[site_id()]),0,0];
    }
    if(!$rows&&!$stats)return null;return ['stats'=>$stats,'table'=>['rows'=>$rows]];
  }
}