<?php
namespace Aio\Services;
use Aio\DB;use PDO;
final class PageData {
 public static function storeState(): array { $p=DB::pdo();
  $cats=$p->prepare("SELECT id,name FROM inventory_categories WHERE site_id=? AND deleted_at IS NULL ORDER BY name");$cats->execute([site_id()]);$catRows=$cats->fetchAll();
  $it=$p->prepare("SELECT i.*,c.name category_name,u.code unit_code,l.name location_name,COALESCE(SUM(b.qty_on_hand),0) stock_qty FROM inventory_items i LEFT JOIN inventory_categories c ON c.id=i.category_id JOIN units u ON u.id=i.stock_unit_id LEFT JOIN stock_locations l ON l.id=i.default_storage_location_id LEFT JOIN stock_balances b ON b.inventory_item_id=i.id WHERE i.site_id=? AND i.deleted_at IS NULL GROUP BY i.id ORDER BY i.name");$it->execute([site_id()]);
  $items=array_map(function($x){$usage=['RECIPE_INGREDIENT'=>'Recipe Ingredient','DIRECT_SALE'=>'Direct Sale','BOTH'=>'Both'][$x['usage_mode']]??$x['usage_mode'];$u=strtoupper((string)$x['unit_code']);$stockUnit=$u==='G'?'g':($u==='ML'?'ml':($u==='PCS'?'piece':$u));return ['id'=>$x['id'],'name'=>$x['name'],'category'=>$x['category_name']??'','stockUnit'=>$stockUnit,'purchaseUnit'=>$x['purchase_unit_name']??'','purchaseFactor'=>(float)$x['purchase_factor'],'stockQty'=>(float)$x['stock_qty'],'avgStockCost'=>(float)$x['avg_cost_per_stock_unit'],'reorderQty'=>(float)$x['reorder_level'],'storage'=>$x['location_name']??'','usage'=>$usage,'batch'=>(bool)$x['track_batch'],'expiry'=>(bool)$x['track_expiry']];},$it->fetchAll());
  $mc=$p->prepare("SELECT mc.name,COALESCE(LOWER(NULLIF(p.station_code,'')),'main') printer FROM menu_categories mc LEFT JOIN menu_category_printer_routes r ON r.category_id=mc.id AND r.is_active=1 AND r.is_primary=1 LEFT JOIN printers p ON p.id=r.printer_id WHERE mc.site_id=? AND mc.deleted_at IS NULL ORDER BY mc.sort_order,mc.name");$mc->execute([site_id()]);$menuCats=$mc->fetchAll();
  $rq=$p->prepare("SELECT mi.id menu_id,mi.name menu_name,mc.name category,mi.consumption_type,mi.direct_inventory_item_id,mi.direct_inventory_qty,r.id recipe_id,r.yield_qty FROM menu_items mi JOIN menu_categories mc ON mc.id=mi.category_id LEFT JOIN recipes r ON r.menu_item_id=mi.id AND r.is_current=1 WHERE mi.site_id=? AND mi.deleted_at IS NULL ORDER BY mi.name");$rq->execute([site_id()]);$recipes=[];
  foreach($rq->fetchAll() as $m){ if($m['consumption_type']==='DIRECT_INVENTORY'){$recipes[]=['id'=>$m['menu_id'],'menuName'=>$m['menu_name'],'category'=>$m['category'],'mode'=>'direct','inventoryItemId'=>$m['direct_inventory_item_id'],'directQty'=>(float)$m['direct_inventory_qty']];} elseif($m['recipe_id']){$iq=$p->prepare("SELECT inventory_item_id itemId,qty_per_yield qty,waste_pct wastePct FROM recipe_ingredients WHERE recipe_id=?");$iq->execute([$m['recipe_id']]);$ing=array_map(fn($x)=>['itemId'=>$x['itemId'],'qty'=>(float)$x['qty'],'wastePct'=>(float)$x['wastePct']],$iq->fetchAll());$recipes[]=['id'=>$m['menu_id'],'menuName'=>$m['menu_name'],'category'=>$m['category'],'mode'=>'recipe','yieldQty'=>(float)$m['yield_qty'],'ingredients'=>$ing];}}
  $po=$p->prepare("SELECT gr.id,gr.grn_no,s.name supplier,DATE_FORMAT(gr.received_at,'%d %b %Y') date,gr.total_amount amount,gr.status,(SELECT COUNT(*) FROM goods_receipt_items gi WHERE gi.goods_receipt_id=gr.id) `lines` FROM goods_receipts gr JOIN suppliers s ON s.id=gr.supplier_id WHERE gr.site_id=? ORDER BY gr.received_at DESC LIMIT 100");$po->execute([site_id()]);
  return ['inventoryCategories'=>array_column($catRows,'name'),'inventoryItems'=>$items,'menuCategories'=>$menuCats,'recipes'=>$recipes,'purchaseOrders'=>$po->fetchAll()]; }
 public static function dashboard(): array { $p=DB::pdo();$date=today();
  $q=$p->prepare("SELECT COALESCE(SUM(grand_total),0) s,COUNT(*) c,COALESCE(SUM(subtotal),0) gross FROM orders WHERE site_id=? AND business_date=? AND order_status='CLOSED'");$q->execute([site_id(),$date]);$a=$q->fetch();
  $cnt=function($sql,$args=[])use($p){$q=$p->prepare($sql);$q->execute($args);return (int)$q->fetchColumn();};
  $running=$cnt("SELECT COUNT(*) FROM orders WHERE site_id=? AND order_status<>'CLOSED'",[site_id()]);$preparing=$cnt("SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status IN ('NEW','PREPARING')",[site_id()]);$ready=$cnt("SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status='READY'",[site_id()]);$delayed=$cnt("SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status IN ('NEW','PREPARING') AND TIMESTAMPDIFF(MINUTE,sent_at,NOW())>=18",[site_id()]);$online=$cnt("SELECT COUNT(*) FROM online_order_details WHERE site_id=? AND acceptance_status='PENDING'",[site_id()]);$riders=$cnt("SELECT COUNT(*) FROM riders WHERE site_id=? AND status IN ('ON_DELIVERY','ON ROAD','ON_DELIVERY')",[site_id()]);$tables=$cnt("SELECT COUNT(*) FROM dining_tables WHERE site_id=? AND is_active=1",[site_id()]);$occ=$cnt("SELECT COUNT(*) FROM dining_tables WHERE site_id=? AND is_active=1 AND status='OCCUPIED'",[site_id()]);
  $pay=['cash'=>0,'card'=>0,'raast'=>0,'walletBank'=>0];$pq=$p->prepare("SELECT pm.code,pm.method_type,SUM(py.amount) amount FROM payments py JOIN payment_methods pm ON pm.id=py.payment_method_id WHERE py.site_id=? AND DATE(py.paid_at)=? AND py.status='COMPLETED' GROUP BY pm.code,pm.method_type");$pq->execute([site_id(),$date]);foreach($pq->fetchAll() as $x){$code=strtoupper($x['code']);$amt=(float)$x['amount'];if($code==='CASH')$pay['cash']+=$amt;elseif($code==='CARD')$pay['card']+=$amt;elseif($code==='RAAST')$pay['raast']+=$amt;else$pay['walletBank']+=$amt;}
  $mix=['dineIn'=>0,'takeaway'=>0,'delivery'=>0,'online'=>0];$mq=$p->prepare("SELECT service_mode,SUM(grand_total) amount FROM orders WHERE site_id=? AND business_date=? AND order_status='CLOSED' GROUP BY service_mode");$mq->execute([site_id(),$date]);foreach($mq->fetchAll() as $x){$m=$x['service_mode'];if($m==='DINE_IN')$mix['dineIn']=(float)$x['amount'];elseif($m==='TAKEAWAY')$mix['takeaway']=(float)$x['amount'];else$mix['delivery']+=(float)$x['amount'];}$oq=$p->prepare("SELECT COALESCE(SUM(o.grand_total),0) FROM online_order_details d JOIN orders o ON o.id=d.order_id WHERE d.site_id=? AND o.business_date=?");$oq->execute([site_id(),$date]);$mix['online']=(float)$oq->fetchColumn();
  $eq=$p->prepare("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE site_id=? AND expense_date=? AND status='APPROVED'");$eq->execute([site_id(),$date]);$expenses=(float)$eq->fetchColumn();$cq=$p->prepare("SELECT COALESCE(SUM(ABS(stl.value_change)),0) FROM stock_transaction_lines stl JOIN stock_transactions st ON st.id=stl.stock_transaction_id WHERE st.site_id=? AND st.business_date=? AND st.transaction_type='SALE'");$cq->execute([site_id(),$date]);$food=(float)$cq->fetchColumn();
  $sq=$p->prepare("SELECT shift_no,opening_cash FROM cashier_shifts WHERE site_id=? AND status='OPEN' ORDER BY opened_at DESC LIMIT 1");$sq->execute([site_id()]);$shift=$sq->fetch()?:['shift_no'=>'—','opening_cash'=>0];
  $hq=$p->prepare("SELECT HOUR(closed_at) h,SUM(grand_total) a FROM orders WHERE site_id=? AND business_date=? AND order_status='CLOSED' GROUP BY HOUR(closed_at)");$hq->execute([site_id(),$date]);$map=[];foreach($hq->fetchAll() as $x)$map[(int)$x['h']]=(float)$x['a'];$hourly=[];foreach(range(10,18) as $h)$hourly[]=$map[$h]??0;
  $bq=$p->prepare("SELECT oi.item_name_snapshot name,SUM(oi.qty) qty,SUM(oi.line_total) sales FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.site_id=? AND o.business_date=? AND o.order_status='CLOSED' GROUP BY oi.item_name_snapshot ORDER BY qty DESC LIMIT 8");$bq->execute([site_id(),$date]);$best=array_map(fn($x)=>['name'=>$x['name'],'qty'=>(float)$x['qty'],'sales'=>(float)$x['sales'],'cost'=>0],$bq->fetchAll());
  return array_merge(['netSales'=>(float)$a['s'],'grossSales'=>(float)$a['gross'],'orders'=>(int)$a['c'],'runningOrders'=>$running,'preparing'=>$preparing,'ready'=>$ready,'delayed'=>$delayed,'onlineNew'=>$online,'ridersRoad'=>$riders,'occupiedTables'=>$occ,'totalTables'=>$tables,'expenses'=>$expenses,'foodCost'=>$food,'shift'=>$shift['shift_no'],'openingCash'=>(float)$shift['opening_cash'],'best'=>$best,'hourly'=>$hourly,'updatedAt'=>date(DATE_ATOM)],$pay,$mix); }
 public static function posBoot(): array { $p=DB::pdo();$date=today();
  $q=$p->prepare("SELECT mi.id,mi.name,mi.description,mi.item_type,mi.base_price,mi.image_url,mc.name category,(SELECT COUNT(*) FROM menu_item_variants v WHERE v.menu_item_id=mi.id AND v.is_active=1) variants FROM menu_items mi LEFT JOIN menu_categories mc ON mc.id=mi.category_id WHERE mi.site_id=? AND mi.is_active=1 AND mi.is_pos=1 AND mi.deleted_at IS NULL ORDER BY COALESCE(mc.sort_order,999),mi.name");$q->execute([site_id()]);$products=[];$i=0;foreach($q->fetchAll() as $x){$stats=[0,0,0];foreach([0,1,7] as $j=>$days){$d=$days===7?date('Y-m-d',strtotime('-6 day')):date('Y-m-d',strtotime('-'.$days.' day'));$sq=$p->prepare($days===7?"SELECT COALESCE(SUM(oi.qty),0) FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.menu_item_id=? AND o.site_id=? AND o.business_date BETWEEN ? AND ? AND o.order_status='CLOSED'":"SELECT COALESCE(SUM(oi.qty),0) FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.menu_item_id=? AND o.site_id=? AND o.business_date=? AND o.order_status='CLOSED'");$args=$days===7?[$x['id'],site_id(),$d,$date]:[$x['id'],site_id(),$d];$sq->execute($args);$stats[$j]=(float)$sq->fetchColumn();}$products[]=['id'=>$x['id'],'name'=>$x['name'],'cat'=>$x['category']?:'General','price'=>(float)$x['base_price'],'weighted'=>$x['item_type']==='WEIGHTED','unit'=>$x['item_type']==='WEIGHTED'?'KG':'','pizza'=>($x['category']??'')==='Pizza'||(int)$x['variants']>0,'desc'=>$x['description']??'','img'=>$x['image_url']?:('/assets/menu_'.str_pad((string)(($i%15)+1),2,'0',STR_PAD_LEFT).'.jpg'),'today'=>$stats[0],'yesterday'=>$stats[1],'days7'=>$stats[2]];$i++;}
  $pr=$p->prepare("SELECT p.id,p.name,p.station_code FROM printers p WHERE p.site_id=? AND p.is_active=1 AND p.printer_type='KITCHEN'");$pr->execute([site_id()]);$printers=[];foreach($pr->fetchAll() as $x){$key=strtolower($x['station_code']?:'main');$printers[$key]=['id'=>$x['id'],'name'=>$x['name'],'station'=>$x['station_code']?:'Kitchen'];}
  $mc=$p->prepare("SELECT mc.name,COALESCE(LOWER(NULLIF(p.station_code,'')),'main') printer FROM menu_categories mc LEFT JOIN menu_category_printer_routes r ON r.category_id=mc.id AND r.is_active=1 AND r.is_primary=1 LEFT JOIN printers p ON p.id=r.printer_id WHERE mc.site_id=? AND mc.deleted_at IS NULL ORDER BY mc.sort_order");$mc->execute([site_id()]);$cats=array_map(fn($x)=>['name'=>$x['name'],'icon'=>'•','printer'=>$x['printer']],$mc->fetchAll());
  $cu=$p->prepare("SELECT c.id,c.full_name name,c.phone,c.customer_type type,ca.address_text address,ca.area FROM customers c LEFT JOIN customer_addresses ca ON ca.customer_id=c.id AND ca.is_default=1 WHERE c.tenant_id=? AND c.status='ACTIVE' ORDER BY c.full_name LIMIT 300");$cu->execute([tenant_id()]);$customers=array_merge([['id'=>'walkin','name'=>'Walk-in Customer','phone'=>'','address'=>'','area'=>'','type'=>'Walk-in']],$cu->fetchAll());
  $tb=$p->prepare("SELECT id,display_name,status,seats FROM dining_tables WHERE site_id=? AND is_active=1 ORDER BY display_name");$tb->execute([site_id()]);$tables=$tb->fetchAll();
  $sh=$p->prepare("SELECT id,shift_no FROM cashier_shifts WHERE site_id=? AND status='OPEN' ORDER BY opened_at DESC LIMIT 1");$sh->execute([site_id()]);$shift=$sh->fetch()?:null;
  $sb=$p->prepare("SELECT o.bill_no,o.closed_at,o.service_mode,o.grand_total,dt.display_name table_name,c.full_name customer_name,pm.name payment_name,fi.provider_invoice_no fbr_no FROM orders o LEFT JOIN dining_tables dt ON dt.id=o.table_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN payments py ON py.order_id=o.id LEFT JOIN payment_methods pm ON pm.id=py.payment_method_id LEFT JOIN fiscal_invoices fi ON fi.order_id=o.id WHERE o.site_id=? AND o.business_date=? AND o.order_status='CLOSED' ORDER BY o.closed_at DESC LIMIT 50");$sb->execute([site_id(),$date]);$shiftBills=[];foreach($sb->fetchAll() as $x){$n=(int)preg_replace('/\D/','',$x['bill_no']);$shiftBills[]=['id'=>$x['bill_no'],'billNo'=>$n?:$x['bill_no'],'time'=>$x['closed_at']?date('h:i A',strtotime($x['closed_at'])):'','mode'=>self::modeLabel($x['service_mode']),'table'=>$x['table_name']?:'—','customer'=>$x['customer_name']?:'Walk-in','amount'=>(float)$x['grand_total'],'payment'=>$x['payment_name']?:'','fbrNo'=>$x['fbr_no']?:''];}
  return ['products'=>$products,'printers'=>$printers,'categories'=>$cats,'customers'=>$customers,'tables'=>$tables,'shift'=>$shift,'shiftBills'=>$shiftBills,'nextBill'=>self::nextBill()]; }
 public static function nextBill(): int {$p=DB::pdo();$q=$p->prepare("SELECT bill_no FROM orders WHERE site_id=? AND business_date=? ORDER BY created_at DESC LIMIT 200");$q->execute([site_id(),today()]);$max=0;foreach($q->fetchAll() as $x){$n=(int)preg_replace('/\D/','',$x['bill_no']);$max=max($max,$n);}return $max+1;}
 public static function moduleData(string $page): ?array { $p=DB::pdo();$money=fn($n)=>'PKR '.number_format((float)$n,0);$tbl=null;$stats=[];
  if($page==='customers.html'){$q=$p->prepare("SELECT full_name,phone,(SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id) orders,(SELECT COALESCE(SUM(grand_total),0) FROM orders o WHERE o.customer_id=c.id AND o.order_status='CLOSED') spend,customer_type FROM customers c WHERE tenant_id=? AND status='ACTIVE' ORDER BY created_at DESC LIMIT 100");$q->execute([tenant_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['full_name'],$x['phone']?:'—',$x['orders'],$money($x['spend']),$x['customer_type'],'<span class="tag green">Active</span>'];$cnt=(int)$p->query("SELECT COUNT(*) FROM customers WHERE status='ACTIVE'")->fetchColumn();$stats=[$cnt,$cnt,0,'PKR 0'];$tbl=['headers'=>['Customer','Phone','Orders','Total Spend','Type','Status'],'rows'=>$rows];}
  elseif($page==='orders_management.html'){$q=$p->prepare("SELECT o.bill_no,o.service_mode,COALESCE(dt.display_name,c.full_name,'Walk-in') target,u.full_name waiter,(SELECT COUNT(*) FROM order_items i WHERE i.order_id=o.id) items,o.grand_total,o.order_status,o.opened_at FROM orders o LEFT JOIN dining_tables dt ON dt.id=o.table_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN users u ON u.id=o.waiter_user_id WHERE o.site_id=? AND o.order_status<>'CLOSED' ORDER BY o.opened_at DESC LIMIT 100");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['bill_no'],self::modeLabel($x['service_mode']),$x['target'],$x['waiter']?:'—',$x['items'],$money($x['grand_total']),$x['order_status'],floor((time()-strtotime($x['opened_at']))/60).'m'];$running=count($rows);$held=self::count($p,"SELECT COUNT(*) FROM orders WHERE site_id=? AND hold_status=1 AND order_status<>'CLOSED'",[site_id()]);$stats=[$running,$held,self::count($p,"SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status IN ('NEW','PREPARING')",[site_id()]),self::count($p,"SELECT COUNT(*) FROM kitchen_tickets WHERE site_id=? AND ticket_status='READY'",[site_id()])];$tbl=['headers'=>['Bill','Mode','Table / Customer','Waiter','Items','Amount','Status','Age'],'rows'=>$rows];}
  elseif($page==='suppliers.html'){$q=$p->prepare("SELECT s.name,s.phone,(SELECT COUNT(*) FROM supplier_items si WHERE si.supplier_id=s.id) items,(SELECT COALESCE(SUM(gr.total_amount),0) FROM goods_receipts gr WHERE gr.supplier_id=s.id AND MONTH(gr.received_at)=MONTH(CURDATE()) AND YEAR(gr.received_at)=YEAR(CURDATE())) mtd,s.status FROM suppliers s WHERE s.tenant_id=? ORDER BY s.name");$q->execute([tenant_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['phone']?:'—',$x['items'],$money($x['mtd']),'PKR 0',$x['status']];$stats=[count($rows),'PKR 0',$money(array_sum(array_map(fn($r)=>(float)str_replace([',','PKR '],'',$r[3]),$rows))),'PKR 0'];$tbl=['headers'=>['Supplier','Contact','Items','MTD Purchases','Outstanding','Status'],'rows'=>$rows];}
  elseif($page==='reservations.html'){$q=$p->prepare("SELECT DATE_FORMAT(reservation_at,'%h:%i %p') tm,guest_name,guest_phone,guest_count,deposit_amount,status FROM reservations WHERE site_id=? AND DATE(reservation_at)>=CURDATE() ORDER BY reservation_at LIMIT 100");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['tm'],$x['guest_name'],$x['guest_phone']?:'—',$x['guest_count'],'—',$money($x['deposit_amount']),$x['status']];$stats=[self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND DATE(reservation_at)=CURDATE()",[site_id()]),self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND reservation_at BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL 2 HOUR)",[site_id()]),self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND status='WAITLIST'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM reservations WHERE site_id=? AND DATE(reservation_at)=CURDATE() AND status='NO_SHOW'",[site_id()])];$tbl=['headers'=>['Time','Customer','Phone','Guests','Table','Deposit','Status'],'rows'=>$rows];}
  elseif($page==='delivery.html'){$q=$p->prepare("SELECT o.bill_no,c.full_name,d.delivery_area,o.grand_total,d.delivery_status,r.name rider FROM delivery_orders d JOIN orders o ON o.id=d.order_id LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN riders r ON r.id=d.rider_id WHERE d.site_id=? ORDER BY o.opened_at DESC LIMIT 100");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['bill_no'],$x['full_name']?:'Walk-in',$x['delivery_area']?:'—',$money($x['grand_total']),'—',$x['delivery_status'],$x['rider']?:'Not Assigned'];$stats=[self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND delivery_status IN ('WAITING','READY')",[site_id()]),self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND delivery_status IN ('PICKED_UP','ON_THE_WAY')",[site_id()]),self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND DATE(delivered_at)=CURDATE()",[site_id()]),'—'];$tbl=['headers'=>['Order','Customer','Area','Amount','Payment','Status','Rider'],'rows'=>$rows];}
  elseif($page==='rider_management.html'){$q=$p->prepare("SELECT name,phone,status,cash_held FROM riders WHERE site_id=? ORDER BY name");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$x['phone']?:'—','—',$money($x['cash_held']),$x['status']];$stats=[count($rows),$money(array_sum(array_map(fn($x)=>(float)$x['cash_held'],$q->fetchAll()?:[]))),self::count($p,"SELECT COUNT(*) FROM delivery_orders WHERE site_id=? AND DATE(delivered_at)=CURDATE()",[site_id()]),'—'];$tbl=['headers'=>['Rider','Phone','Current Order','COD Held','Status'],'rows'=>$rows];}
  elseif($page==='expenses.html'){$q=$p->prepare("SELECT e.expense_no,ec.name category,e.amount,u.full_name,e.status FROM expenses e JOIN expense_categories ec ON ec.id=e.category_id LEFT JOIN users u ON u.id=e.created_by_user_id WHERE e.site_id=? ORDER BY e.expense_date DESC,e.created_at DESC LIMIT 100");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['expense_no'],$x['category'],$money($x['amount']),$x['full_name']?:'—',$x['status']];$today=self::sum($p,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE site_id=? AND expense_date=CURDATE()",[site_id()]);$month=self::sum($p,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE site_id=? AND MONTH(expense_date)=MONTH(CURDATE()) AND YEAR(expense_date)=YEAR(CURDATE())",[site_id()]);$stats=[$money($today),$money($month),self::count($p,"SELECT COUNT(*) FROM expenses WHERE site_id=? AND status='PENDING'",[site_id()]),'—'];$tbl=['headers'=>['Expense','Category','Amount','User','Status'],'rows'=>$rows];}
  elseif($page==='fbr.html'){$q=$p->prepare("SELECT o.bill_no,f.provider_invoice_no,f.status,f.retry_count FROM fiscal_invoices f JOIN orders o ON o.id=f.order_id WHERE f.site_id=? ORDER BY f.submitted_at DESC LIMIT 100");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['bill_no'],$x['provider_invoice_no']?:'Pending',$x['status'],$x['retry_count']];$stats=['Configured',self::count($p,"SELECT COUNT(*) FROM fiscal_invoices WHERE site_id=? AND DATE(COALESCE(submitted_at,NOW()))=CURDATE()",[site_id()]),'—',self::count($p,"SELECT COUNT(*) FROM fiscal_invoices WHERE site_id=? AND status IN ('FAILED','PENDING')",[site_id()])];$tbl=['headers'=>['Bill','FBR Invoice','Status','Retries'],'rows'=>$rows];}
  elseif($page==='printer_devices.html'){$q=$p->prepare("SELECT name,station_code,CONCAT(COALESCE(ip_address,''),IF(port_no IS NULL,'',CONCAT(':',port_no))) addr,printer_type,IF(is_active=1,'Online','Disabled') status FROM printers WHERE site_id=? ORDER BY name");$q->execute([site_id()]);$rows=array_map(fn($x)=>[$x['name'],$x['station_code']?:'—',$x['addr'],$x['printer_type'],$x['status']],$q->fetchAll());$stats=[self::count($p,"SELECT COUNT(*) FROM printers WHERE site_id=? AND printer_type='RECEIPT' AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM printers WHERE site_id=? AND printer_type='KITCHEN' AND is_active=1",[site_id()]),self::count($p,"SELECT COUNT(*) FROM devices WHERE site_id=? AND device_type='KDS' AND status='ACTIVE'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM devices WHERE site_id=? AND status='ACTIVE'",[site_id()])];$tbl=['headers'=>['Printer','Station','IP / Port','Type','Status'],'rows'=>$rows];}
  elseif($page==='multi_branch.html'){$q=$p->prepare("SELECT s.name,(SELECT COALESCE(SUM(o.grand_total),0) FROM orders o WHERE o.site_id=s.id AND o.business_date=CURDATE() AND o.order_status='CLOSED') sales,(SELECT COUNT(*) FROM orders o WHERE o.site_id=s.id AND o.business_date=CURDATE()) orders,s.status FROM sites s WHERE s.tenant_id=? ORDER BY s.name");$q->execute([tenant_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['name'],$money($x['sales']),$x['orders'],'—','—',$x['status']];$stats=[count($rows),$money(array_sum(array_map(fn($x)=>(float)$x[1],[]))),0,0];$tbl=['headers'=>['Branch','Sales Today','Orders','Stock Value','Open Shift','Status'],'rows'=>$rows];}
  elseif($page==='stock_transfer.html'){$q=$p->prepare("SELECT transfer_no,(SELECT name FROM sites WHERE id=t.from_site_id) fr,(SELECT name FROM sites WHERE id=t.to_site_id) too,transfer_date,status FROM stock_transfers t WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100");$q->execute([tenant_id()]);$rows=array_map(fn($x)=>[$x['transfer_no'],$x['fr'],$x['too'],'—','—',$x['status']],$q->fetchAll());$stats=[self::count($p,"SELECT COUNT(*) FROM stock_transfers WHERE tenant_id=? AND status LIKE 'PENDING%'",[tenant_id()]),self::count($p,"SELECT COUNT(*) FROM stock_transfers WHERE tenant_id=? AND status='IN_TRANSIT'",[tenant_id()]),self::count($p,"SELECT COUNT(*) FROM stock_transfers WHERE tenant_id=? AND DATE(received_at)=CURDATE()",[tenant_id()]),0];$tbl=['headers'=>['Transfer','From','To','Items','Value','Status'],'rows'=>$rows];}
  elseif($page==='void_refund.html'){$q=$p->prepare("SELECT DATE_FORMAT(created_at,'%h:%i %p') tm,(SELECT bill_no FROM orders WHERE id=v.order_id) bill,'Item Void' type,void_qty,reason_code,approval_status FROM order_item_voids v WHERE site_id=? ORDER BY created_at DESC LIMIT 100");$q->execute([site_id()]);$rows=[];foreach($q->fetchAll() as $x)$rows[]=[$x['tm'],$x['bill'],$x['type'],$x['void_qty'],$x['reason_code'],$x['approval_status']];$stats=[count($rows),self::count($p,"SELECT COUNT(*) FROM order_item_voids WHERE site_id=? AND approval_status='APPROVED'",[site_id()]),self::count($p,"SELECT COUNT(*) FROM refunds WHERE site_id=? AND DATE(created_at)=CURDATE()",[site_id()]),self::count($p,"SELECT COUNT(*) FROM refunds WHERE site_id=? AND status='PENDING'",[site_id()])];$tbl=['headers'=>['Time','Bill','Type','Qty / Amount','Reason','Status'],'rows'=>$rows];}
  return ($tbl||$stats)?['stats'=>$stats,'table'=>$tbl]:null; }
 private static function count(PDO $p,string $sql,array $a):int{$q=$p->prepare($sql);$q->execute($a);return(int)$q->fetchColumn();}
 private static function sum(PDO $p,string $sql,array $a):float{$q=$p->prepare($sql);$q->execute($a);return(float)$q->fetchColumn();}
 private static function modeLabel(string $m):string{return ['DINE_IN'=>'Dine In','TAKEAWAY'=>'Takeaway','DELIVERY'=>'Home Delivery'][$m]??$m;}
}

// build: V17.1 build 2026-08-25
