<?php
use Aio\Auth;
if (!isset($pageTitle)) $pageTitle='Restaurant OS';
$route=$_GET['r']??'dashboard';
$publicRoutes=['login','signup','signup-pending','setup'];
if(in_array($route,$publicRoutes,true)){ include $viewFile; return; }
$groups=[
'Operations'=>[['dashboard','Dashboard'],['shift','Opening & Closing Shift'],['pos','Sale Point / POS'],['tablet','Order Taker Tablet'],['kds','Kitchen / KDS'],['tables','Tables & Floors'],['orders','Running Orders'],['online','Online Orders']],
'Inventory & Menu'=>[['inventory','Inventory'],['purchasing','Purchasing'],['recipe','Recipe & Food Cost'],['menu','Menu & Categories'],['wastage','Wastage / Adjustment'],['transfer','Stock Transfer'],['stock-count','Physical Stock Count'],['suppliers','Suppliers']],
'Customers & Delivery'=>[['customers','Customers'],['customer-web','Customer Web / QR'],['delivery','Delivery'],['riders','Rider Management'],['reservations','Reservations'],['loyalty','Loyalty / Membership'],['notifications','WhatsApp / Notifications']],
'Finance & Reports'=>[['expenses','Expenses'],['accounting','Accounting / Cash'],['promotions','Discounts / Promotions'],['void-refund','Void / Refund'],['reports','Reports'],['fbr','FBR / Digital Invoice']],
'System'=>[['printers','Printers / Devices'],['branches','Multi-Branch'],['offline','Offline / Sync'],['users','Users & Access'],['settings','Settings']]
];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($pageTitle)?></title><link rel="stylesheet" href="/assets/app.css"></head><body><div class="app"><aside class="sidebar"><div class="logo"><div class="logo-mark">A</div><div><strong>All-in-One</strong><small>Restaurant Operating System</small></div></div><div class="branch"><span>Current Branch</span><b>Islamabad — F10</b><small><?=cfg('app.sync_enabled')?'Cloud Sync Enabled':'Local Mode / Sync Disabled'?></small></div><nav class="nav"><a href="/?r=dashboard" class="<?=$route==='dashboard'?'active':''?>">Dashboard</a><?php foreach($groups as $g=>$items):?><details><summary><?=$g?><span>›</span></summary><div class="sub"><?php foreach($items as [$r,$label]): if(!Auth::canModule(str_replace('-','_',$r)) && !in_array($r,['stock-count','customer-web','void-refund','notifications'],true)) continue;?><a href="/?r=<?=$r?>" class="<?=$route===$r?'active':''?>"><?=$label?></a><?php endforeach;?></div></details><?php endforeach;?></nav></aside><main class="main"><header class="header"><div><h1><?=e($pageTitle)?></h1><p><?=e($pageSubtitle??'Local-first restaurant management')?></p></div><div class="spacer"></div><span class="tag green">Local DB</span><a class="btn" href="/?r=users">Users</a><a class="btn" href="/?r=logout">Logout</a></header><div class="content"><?php if($m=flash('ok')):?><div class="flash ok"><?=e($m)?></div><?php endif;?><?php if($m=flash('err')):?><div class="flash err"><?=e($m)?></div><?php endif;?><?php include $viewFile;?></div></main></div><script src="/assets/app.js"></script></body></html>
// build: V17.1 build 2026-08-25
