
(function(){
 const KEY='urban_spoon_access_v5';
 const MODULES=[{"key": "dashboard", "label": "Dashboard", "href": "index.html"}, {"key": "shift", "label": "Opening & Closing Shift", "href": "shift_management.html"}, {"key": "pos", "label": "Sale Point / POS", "href": "restaurant_pos.html"}, {"key": "tablet", "label": "Order Taker Tablet", "href": "restaurant_order_taker_tablet.html"}, {"key": "kds", "label": "Kitchen / KDS", "href": "kds.html"}, {"key": "tables", "label": "Tables & Floors", "href": "tables_floors.html"}, {"key": "orders", "label": "Running Orders", "href": "orders_management.html"}, {"key": "online", "label": "Online Orders", "href": "online_orders.html"}, {"key": "inventory", "label": "Inventory", "href": "inventory_creation.html"}, {"key": "purchasing", "label": "Purchasing", "href": "purchasing.html"}, {"key": "recipe", "label": "Recipe & Food Cost", "href": "recipe_making.html"}, {"key": "menu", "label": "Menu & Categories", "href": "menu_management.html"}, {"key": "wastage", "label": "Wastage / Adjustment", "href": "wastage_adjustment.html"}, {"key": "transfer", "label": "Stock Transfer", "href": "stock_transfer.html"}, {"key": "count", "label": "Physical Stock Count", "href": "stock_count.html"}, {"key": "suppliers", "label": "Suppliers", "href": "suppliers.html"}, {"key": "customers", "label": "Customers", "href": "customers.html"}, {"key": "customer_app", "label": "Customer Mobile App", "href": "customer_mobile_app.html"}, {"key": "customer_web", "label": "Customer Web / QR", "href": "customer_web_qr.html"}, {"key": "delivery", "label": "Delivery", "href": "delivery.html"}, {"key": "riders", "label": "Rider Management", "href": "rider_management.html"}, {"key": "reservations", "label": "Reservations", "href": "reservations.html"}, {"key": "loyalty", "label": "Loyalty / Membership", "href": "loyalty.html"}, {"key": "whatsapp", "label": "WhatsApp / Notifications", "href": "whatsapp_notifications.html"}, {"key": "expenses", "label": "Expenses", "href": "expenses.html"}, {"key": "accounting", "label": "Accounting / Cash", "href": "accounting.html"}, {"key": "promotions", "label": "Discounts / Promotions", "href": "discounts_promotions.html"}, {"key": "staff", "label": "Staff / Roles", "href": "staff_roles.html"}, {"key": "void", "label": "Void / Refund", "href": "void_refund.html"}, {"key": "reports", "label": "Reports", "href": "reports.html"}, {"key": "fbr", "label": "FBR / Digital Invoice", "href": "fbr.html"}, {"key": "printers", "label": "Printers / Devices", "href": "printer_devices.html"}, {"key": "branches", "label": "Multi-Branch", "href": "multi_branch.html"}, {"key": "offline", "label": "Offline / Sync", "href": "offline_sync.html"}, {"key": "users", "label": "Users & Access", "href": "users_access.html"}, {"key": "settings", "label": "Settings", "href": "settings.html"}];
 const roleDefaults={
  'Owner / Admin':MODULES.map(m=>m.key),
  'Branch Manager':['dashboard','shift','pos','tablet','kds','tables','orders','online','inventory','purchasing','recipe','menu','wastage','transfer','count','suppliers','customers','delivery','riders','reservations','loyalty','expenses','accounting','promotions','staff','void','reports','fbr','printers','offline','users','settings'],
  'Cashier':['dashboard','shift','pos','orders','customers','void'],
  'Waiter':['dashboard','tablet','tables','orders'],
  'Chef / Kitchen':['dashboard','kds','orders','inventory'],
  'Storekeeper':['dashboard','inventory','purchasing','recipe','wastage','transfer','count','suppliers','reports'],
  'Accountant':['dashboard','shift','expenses','accounting','reports','suppliers','fbr'],
  'Rider':['dashboard','delivery','riders'],
  'Marketing':['dashboard','customers','customer_app','customer_web','loyalty','whatsapp','promotions','reports']
 };
 function uid(p='u'){return p+'-'+Date.now()+'-'+Math.floor(Math.random()*9999)}
 function seed(){return {users:[
  {id:'admin-1',name:'System Administrator',email:'admin@urbanspoon.local',phone:'0300-0000000',password:'Admin@123',role:'Owner / Admin',status:'Active',branch:'All Branches',modules:roleDefaults['Owner / Admin'],permissions:{view:true,add:true,edit:true,delete:true,approve:true}},
  {id:'cashier-1',name:'Ali Raza',email:'ali@urbanspoon.local',phone:'0301-1112233',password:'1234',role:'Cashier',status:'Active',branch:'Islamabad — F10',modules:roleDefaults['Cashier'],permissions:{view:true,add:true,edit:true,delete:false,approve:false}}
 ],requests:[{id:'req-demo',name:'Hamza Khan',email:'hamza@example.com',phone:'0321-4455667',business:'Urban Spoon',password:'1234',requestedAt:'24 Aug 2026 · 2:30 PM',status:'Pending'}],roles:Object.keys(roleDefaults).map((name,i)=>({id:'role-'+i,name,modules:roleDefaults[name]}))}}
 function save(s){localStorage.setItem(KEY,JSON.stringify(s));return s}
 function get(){try{const v=localStorage.getItem(KEY);if(v)return JSON.parse(v)}catch(e){}return save(seed())}
 function signup(data){const s=get();if(s.users.some(u=>u.email.toLowerCase()===data.email.toLowerCase())||s.requests.some(r=>r.email.toLowerCase()===data.email.toLowerCase()))return {ok:false,message:'Email already registered or pending'};const r={id:uid('req'),name:data.name,email:data.email,phone:data.phone,business:data.business||'Restaurant',password:data.password,requestedAt:new Date().toLocaleString(),status:'Pending'};s.requests.unshift(r);save(s);return {ok:true,request:r}}
 function createUser(data){const s=get();if(s.users.some(u=>u.email.toLowerCase()===data.email.toLowerCase()))return {ok:false,message:'Email already exists'};const u={id:uid('user'),name:data.name,email:data.email,phone:data.phone||'',password:data.password||'1234',role:data.role,branch:data.branch||'Islamabad — F10',status:'Active',modules:data.modules||[],permissions:data.permissions||{view:true,add:false,edit:false,delete:false,approve:false}};s.users.unshift(u);save(s);return {ok:true,user:u}}
 function approveRequest(id,data){const s=get(),idx=s.requests.findIndex(r=>r.id===id);if(idx<0)return {ok:false,message:'Request not found'};const r=s.requests[idx];const u={id:uid('user'),name:r.name,email:r.email,phone:r.phone,password:r.password||'1234',role:data.role,branch:data.branch||'Islamabad — F10',status:'Active',modules:data.modules||[],permissions:data.permissions||{view:true,add:false,edit:false,delete:false,approve:false}};s.users.unshift(u);s.requests.splice(idx,1);save(s);return {ok:true,user:u}}
 function rejectRequest(id){const s=get();s.requests=s.requests.filter(r=>r.id!==id);save(s)}
 function updateUser(id,data){const s=get(),u=s.users.find(x=>x.id===id);if(!u)return {ok:false};Object.assign(u,data);save(s);return {ok:true,user:u}}
 function login(email,password){const s=get(),u=s.users.find(x=>x.email.toLowerCase()===(email||'').toLowerCase()&&x.password===password&&x.status==='Active');if(!u)return {ok:false,message:'Invalid login or account not approved'};sessionStorage.setItem('urban_spoon_current_user',JSON.stringify(u));return {ok:true,user:u}}
 function current(){try{return JSON.parse(sessionStorage.getItem('urban_spoon_current_user')||'null')}catch(e){return null}}
 function logout(){sessionStorage.removeItem('urban_spoon_current_user')}
 window.RestaurantAccess={KEY,MODULES,roleDefaults,get,save,signup,createUser,approveRequest,rejectRequest,updateUser,login,current,logout};
})();

/* build: V17.1 build 2026-08-25 */
