<?php
declare(strict_types=1);require_once dirname(__DIR__).'/src/bootstrap.php';
use Aio\DB;use Aio\Services\InventoryService;use Aio\Services\RecipeService;
$p=DB::pdo();
function one($p,$sql,$a=[]){$q=$p->prepare($sql);$q->execute($a);return$q->fetchColumn();}
// ensure floor/tables
if(!(int)one($p,"SELECT COUNT(*) FROM floors WHERE site_id=?",[site_id()])){$fid=uuid();$p->prepare("INSERT INTO floors(id,tenant_id,site_id,name,sort_order) VALUES(?,?,?,'Ground Floor',1)")->execute([$fid,tenant_id(),site_id()]);for($i=1;$i<=30;$i++)$p->prepare("INSERT INTO dining_tables(id,tenant_id,site_id,floor_id,table_code,display_name,seats,status,is_active) VALUES(?,?,?,?,?,?,4,'AVAILABLE',1)")->execute([uuid(),tenant_id(),site_id(),$fid,'T'.$i,'Table '.$i]);}
// customers
if(!(int)one($p,"SELECT COUNT(*) FROM customers WHERE tenant_id=?",[tenant_id()])){foreach([['Ahmed Khan','03001234567','REGULAR','House 22, Street 14, F-10/2, Islamabad','F-10'],['Sarah Malik','03214455667','VIP','Flat 8B, Blue Area, Islamabad','Blue Area'],['Usman Ali','03339988776','CORPORATE','Office 4, I-8 Markaz, Islamabad','I-8'],['Hina Shah','03057772211','REGULAR','G-11, Islamabad','G-11']] as $c){$id=uuid();$p->prepare("INSERT INTO customers(id,tenant_id,site_id,full_name,phone,customer_type,status) VALUES(?,?,?,?,?,?,'ACTIVE')")->execute([$id,tenant_id(),site_id(),$c[0],$c[1],$c[2]]);$p->prepare("INSERT INTO customer_addresses(id,customer_id,label,address_text,area,is_default) VALUES(?,?,'Home',?,?,1)")->execute([uuid(),$id,$c[3],$c[4]]);}}
// inventory categories if missing
$catNames=['Meat & Poultry','Vegetables','Dairy','Dry Grocery','Beverages','Bakery','Packaging','Sauces & Spices'];foreach($catNames as $n){if(!one($p,"SELECT id FROM inventory_categories WHERE site_id=? AND name=?",[site_id(),$n]))InventoryService::createCategory($n);}
$unit=function($code)use($p){return one($p,"SELECT id FROM units WHERE code=?",[$code]);};$loc=function($name)use($p){return one($p,"SELECT id FROM stock_locations WHERE site_id=? AND name=?",[site_id(),$name])?:one($p,"SELECT id FROM stock_locations WHERE site_id=? ORDER BY name LIMIT 1",[site_id()]);};$cat=function($n)use($p){return one($p,"SELECT id FROM inventory_categories WHERE site_id=? AND name=?",[site_id(),$n]);};
$inventory=[
['Boneless Chicken','Meat & Poultry','G','KG',1000,15.8*1000,.72,8000,'Cold Room','RECIPE_INGREDIENT'],['Basmati Rice','Dry Grocery','G','KG',1000,42000,.41,12000,'Dry Store','RECIPE_INGREDIENT'],['Mozzarella Cheese','Dairy','G','KG',1000,2400,1.89,4000,'Cold Room','RECIPE_INGREDIENT'],['Tomato','Vegetables','G','KG',1000,18000,.18,6000,'Cold Room','RECIPE_INGREDIENT'],['Cooking Oil','Dry Grocery','ML','Litre',1000,38000,.515,10000,'Dry Store','RECIPE_INGREDIENT'],['Mint Leaves','Vegetables','G','KG',1000,3200,.29,1000,'Cold Room','RECIPE_INGREDIENT'],['Burger Bun','Bakery','PCS','Piece',1,86,42,30,'Dry Store','RECIPE_INGREDIENT'],['Biryani Spice Mix','Sauces & Spices','G','KG',1000,6500,1.08,1500,'Dry Store','RECIPE_INGREDIENT'],['Coke Tin 330ml','Beverages','PCS','Carton (24)',24,120,95,48,'Bar Store','BOTH'],['Mineral Water 500ml','Beverages','PCS','Carton (24)',24,144,34,48,'Bar Store','DIRECT_SALE']];
foreach($inventory as $x){if(one($p,"SELECT id FROM inventory_items WHERE site_id=? AND name=?",[site_id(),$x[0]]))continue;InventoryService::createItem(['name'=>$x[0],'category_id'=>$cat($x[1]),'sku'=>'','barcode'=>'','usage_mode'=>$x[9],'stock_unit_id'=>$unit($x[2]),'purchase_unit_name'=>$x[3],'purchase_factor'=>$x[4],'avg_cost'=>$x[6],'reorder_level'=>$x[7],'opening_qty'=>$x[5],'location_id'=>$loc($x[8])]);}
// menu categories guaranteed by SQL seed. helper ids
$mcat=function($n)use($p){return one($p,"SELECT id FROM menu_categories WHERE site_id=? AND name=?",[site_id(),$n]);};$inv=function($n)use($p){return one($p,"SELECT id FROM inventory_items WHERE site_id=? AND name=?",[site_id(),$n]);};
$menu=[
['Chicken Biryani','Pakistani',750,'Basmati rice with tender chicken','STANDARD','RECIPE','menu_01.jpg',[['Boneless Chicken',180],['Basmati Rice',160],['Cooking Oil',35],['Tomato',80],['Biryani Spice Mix',10]]],
['Fajita Pizza','Pizza',1050,'Fajita chicken, capsicum & mozzarella','VARIANT','RECIPE','menu_02.jpg',[['Boneless Chicken',120],['Mozzarella Cheese',110],['Tomato',70],['Cooking Oil',18]]],
['Chicken Seekh Kabab','BBQ',650,'6 pieces with mint raita','STANDARD','RECIPE','menu_03.jpg',[['Boneless Chicken',220],['Biryani Spice Mix',12]]],
['Zinger Burger','Fast Food',560,'Crispy fillet, cheese & mayo','STANDARD','RECIPE','menu_04.jpg',[['Boneless Chicken',150],['Burger Bun',1],['Cooking Oil',30]]],
['Chicken Karahi','Pakistani',1250,'Traditional karahi with fresh spices','WEIGHTED','RECIPE','menu_05.jpg',[['Boneless Chicken',500],['Tomato',250],['Cooking Oil',60],['Biryani Spice Mix',15]]],
['Chicken Tikka Boneless','BBQ',950,'Boneless chicken cubes with special spices','STANDARD','RECIPE','menu_06.jpg',[['Boneless Chicken',250],['Biryani Spice Mix',12]]],
['French Fries','Sides',320,'Crispy golden fries with ketchup','STANDARD','NONE','menu_07.jpg',[]],
['Mint Margarita','Drinks',280,'Mint, lime and soda','STANDARD','RECIPE','menu_08.jpg',[['Mint Leaves',12]]],
['Chocolate Lava Cake','Desserts',650,'Warm cake with ice cream','STANDARD','NONE','menu_09.jpg',[]],
['Cold Coffee','Drinks',350,'Chilled coffee with ice cream','STANDARD','NONE','menu_10.jpg',[]],
['Sweet Lassi','Drinks',220,'Traditional creamy lassi','STANDARD','NONE','menu_11.jpg',[]],
['Garlic Naan','Pakistani',120,'Soft naan with garlic & herbs','STANDARD','NONE','menu_12.jpg',[]],
['Chicken Handi','Pakistani',1680,'Creamy handi, family favorite','STANDARD','RECIPE','menu_13.jpg',[['Boneless Chicken',500],['Cooking Oil',50],['Tomato',180]]],
['BBQ Wings','BBQ',790,'Smoky wings with house sauce','STANDARD','RECIPE','menu_14.jpg',[['Boneless Chicken',300],['Biryani Spice Mix',12]]],
['Family Pizza Deal','Pizza',2890,'Large pizza + drinks + fries','COMBO','NONE','menu_15.jpg',[]],
['Coke Tin','Drinks',180,'Chilled 330ml can','STANDARD','DIRECT_INVENTORY','menu_10.jpg',[]],['Mineral Water','Drinks',100,'500ml chilled bottle','STANDARD','DIRECT_INVENTORY','menu_08.jpg',[]]
];
foreach($menu as $x){$existing=one($p,"SELECT id FROM menu_items WHERE site_id=? AND name=?",[site_id(),$x[0]]);if($existing)continue;$id=uuid();$direct=$x[5]==='DIRECT_INVENTORY'?($x[0]==='Coke Tin'?$inv('Coke Tin 330ml'):$inv('Mineral Water 500ml')):null;$p->prepare("INSERT INTO menu_items(id,tenant_id,site_id,category_id,name,description,item_type,consumption_type,direct_inventory_item_id,direct_inventory_qty,base_price,image_url,is_active,is_online,is_pos) VALUES(?,?,?,?,?,?,?,?,?,?,?, ?,1,1,1)")->execute([$id,tenant_id(),site_id(),$mcat($x[1]),$x[0],$x[3],$x[4],$x[5],$direct,$direct?1:null,$x[2],'/assets/'.$x[6]]);if($x[5]==='RECIPE'){$rid=uuid();$p->prepare("INSERT INTO recipes(id,tenant_id,site_id,menu_item_id,version_no,yield_qty,is_current,created_at) VALUES(?,?,?,?,1,1,1,NOW(6))")->execute([$rid,tenant_id(),site_id(),$id]);$cost=0;foreach($x[7] as $ing){$iid=$inv($ing[0]);$uc=(float)one($p,"SELECT avg_cost_per_stock_unit FROM inventory_items WHERE id=?",[$iid]);$lc=$uc*$ing[1];$cost+=$lc;$p->prepare("INSERT INTO recipe_ingredients(id,recipe_id,inventory_item_id,qty_per_yield,waste_pct,line_cost) VALUES(?,?,?,?,0,?)")->execute([uuid(),$rid,$iid,$ing[1],$lc]);}$p->prepare("UPDATE recipes SET food_cost_amount=? WHERE id=?")->execute([$cost,$rid]);}}
// pizza variants
$fp=one($p,"SELECT id FROM menu_items WHERE site_id=? AND name='Fajita Pizza'",[site_id()]);if($fp && !(int)one($p,"SELECT COUNT(*) FROM menu_item_variants WHERE menu_item_id=?",[$fp]))foreach([['Small',1050,1],['Medium',1450,0],['Large',1890,0]] as $v)$p->prepare("INSERT INTO menu_item_variants(id,tenant_id,site_id,menu_item_id,name,price,is_default,is_active) VALUES(?,?,?,?,?,?,?,1)")->execute([uuid(),tenant_id(),site_id(),$fp,$v[0],$v[1],$v[2]]);
echo "Restaurant approved UI demo master data ready.\n";
