<?php
require_once dirname(__DIR__).'/src/bootstrap.php';
use Aio\DB;
$pdo=DB::pdo();
$modules=[
'dashboard'=>'Dashboard','shift'=>'Opening & Closing Shift','pos'=>'Sale Point / POS','tablet'=>'Order Taker Tablet','kds'=>'Kitchen / KDS','tables'=>'Tables & Floors','orders'=>'Running Orders','online'=>'Online Orders','inventory'=>'Inventory','purchasing'=>'Purchasing','recipe'=>'Recipe & Food Cost','menu'=>'Menu & Categories','wastage'=>'Wastage / Adjustment','transfer'=>'Stock Transfer','count'=>'Physical Stock Count','suppliers'=>'Suppliers','customers'=>'Customers','customer_app'=>'Customer Mobile App','customer_web'=>'Customer Web / QR','delivery'=>'Delivery','riders'=>'Rider Management','reservations'=>'Reservations','loyalty'=>'Loyalty / Membership','whatsapp'=>'WhatsApp / Notifications','expenses'=>'Expenses','accounting'=>'Accounting / Cash','promotions'=>'Discounts / Promotions','staff'=>'Staff / Roles','void'=>'Void / Refund','reports'=>'Reports','fbr'=>'FBR / Digital Invoice','printers'=>'Printers / Devices','branches'=>'Multi-Branch','offline'=>'Offline / Sync','users'=>'Users & Access','settings'=>'Settings'];
$sort=1;foreach($modules as $key=>$name){$q=$pdo->prepare('SELECT id FROM platform_modules WHERE module_key=?');$q->execute([$key]);if(!$q->fetchColumn())$pdo->prepare("INSERT INTO platform_modules(id,module_key,name,industry_code,sort_order,is_active) VALUES(?,?,?,'RESTAURANT',?,1)")->execute([uuid(),$key,$name,$sort]);$sort++;}
$roles=['Owner / Admin'=>null,'Branch Manager'=>['dashboard','shift','pos','tablet','kds','tables','orders','online','inventory','purchasing','recipe','menu','wastage','transfer','count','suppliers','customers','delivery','riders','reservations','loyalty','expenses','accounting','promotions','void','reports','fbr','printers','offline','users','settings'],'Cashier'=>['dashboard','shift','pos','orders','customers','void'],'Waiter'=>['dashboard','tablet','tables','orders'],'Chef / Kitchen'=>['dashboard','kds','orders','inventory'],'Storekeeper'=>['dashboard','inventory','purchasing','recipe','wastage','transfer','count','suppliers','reports'],'Accountant'=>['dashboard','shift','expenses','accounting','reports','suppliers','fbr'],'Rider'=>['dashboard','delivery','riders'],'Marketing'=>['dashboard','customers','loyalty','promotions','reports']];
foreach($roles as $name=>$keys){$q=$pdo->prepare('SELECT id FROM roles WHERE tenant_id=? AND name=?');$q->execute([tenant_id(),$name]);$rid=$q->fetchColumn();if(!$rid){$rid=uuid();$pdo->prepare('INSERT INTO roles(id,tenant_id,name,is_system,is_active) VALUES(?,?,?,1,1)')->execute([$rid,tenant_id(),$name]);}if($keys){foreach($keys as $k){$m=$pdo->prepare('SELECT id FROM platform_modules WHERE module_key=?');$m->execute([$k]);if($mid=$m->fetchColumn()){$e=$pdo->prepare('SELECT COUNT(*) FROM role_modules WHERE role_id=? AND module_id=?');$e->execute([$rid,$mid]);if(!$e->fetchColumn())$pdo->prepare('INSERT INTO role_modules(id,role_id,module_id,is_allowed) VALUES(?,?,?,1)')->execute([uuid(),$rid,$mid]);}}}}
echo "Roles seeded.\n";

// build: V17.1 build 2026-08-25
