-- =========================================================
-- LOCAL EDGE DATABASE
-- MySQL 8.0+
-- Generated for the All-in-One Multi-Industry Platform
-- First vertical: Restaurant
-- =========================================================
CREATE DATABASE IF NOT EXISTS `aio_local`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `aio_local`;


-- =========================================================
-- COMMON CORE + RESTAURANT OPERATIONAL SCHEMA
-- Same table definitions are used in cloud and local DB.
-- Local DB normally contains only one tenant/site's data.
-- IDs are UUID strings generated by the application.
-- =========================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE schema_migrations (
    version         VARCHAR(60) NOT NULL,
    description     VARCHAR(255) NULL,
    applied_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (version)
) ENGINE=InnoDB;

CREATE TABLE tenants (
    id              CHAR(36) NOT NULL,
    code            VARCHAR(80) NOT NULL,
    name            VARCHAR(180) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    timezone        VARCHAR(80) NOT NULL DEFAULT 'Asia/Karachi',
    default_currency VARCHAR(10) NOT NULL DEFAULT 'PKR',
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at      DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tenant_code (code)
) ENGINE=InnoDB;

CREATE TABLE organizations (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    parent_org_id       CHAR(36) NULL,
    organization_type   VARCHAR(40) NOT NULL, -- BUSINESS / EDUCATION / HOSPITALITY / HEALTHCARE / SERVICE / OTHER
    industry_code       VARCHAR(60) NOT NULL, -- RESTAURANT first; future RETAIL, PHARMACY...
    name                VARCHAR(180) NOT NULL,
    legal_name          VARCHAR(220) NULL,
    tax_no              VARCHAR(80) NULL,
    email               VARCHAR(190) NULL,
    phone               VARCHAR(50) NULL,
    address_text        VARCHAR(500) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at          DATETIME(6) NULL,
    PRIMARY KEY (id),
    KEY ix_org_tenant (tenant_id),
    KEY ix_org_parent (parent_org_id),
    CONSTRAINT fk_org_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_org_parent FOREIGN KEY (parent_org_id) REFERENCES organizations(id)
) ENGINE=InnoDB;

CREATE TABLE sites (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    organization_id     CHAR(36) NOT NULL,
    code                VARCHAR(80) NOT NULL,
    name                VARCHAR(180) NOT NULL,
    site_type           VARCHAR(40) NOT NULL DEFAULT 'BRANCH', -- BRANCH / WAREHOUSE / CAMPUS / CLINIC...
    timezone            VARCHAR(80) NOT NULL DEFAULT 'Asia/Karachi',
    currency            VARCHAR(10) NOT NULL DEFAULT 'PKR',
    address_text        VARCHAR(500) NULL,
    phone               VARCHAR(50) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at          DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_site_org_code (organization_id, code),
    KEY ix_site_tenant (tenant_id),
    CONSTRAINT fk_site_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_site_org FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB;

CREATE TABLE platform_modules (
    id              CHAR(36) NOT NULL,
    module_key      VARCHAR(80) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    industry_code   VARCHAR(60) NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_platform_module_key (module_key)
) ENGINE=InnoDB;

CREATE TABLE site_modules (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    module_id       CHAR(36) NOT NULL,
    is_enabled      TINYINT(1) NOT NULL DEFAULT 1,
    config_json     JSON NULL,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_site_module (site_id, module_id),
    CONSTRAINT fk_sm_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sm_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_sm_module FOREIGN KEY (module_id) REFERENCES platform_modules(id)
) ENGINE=InnoDB;

CREATE TABLE users (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    username            VARCHAR(120) NULL,
    email               VARCHAR(190) NOT NULL,
    phone               VARCHAR(50) NULL,
    full_name           VARCHAR(180) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    password_algo       VARCHAR(30) NOT NULL DEFAULT 'ARGON2ID',
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_tenant_admin     TINYINT(1) NOT NULL DEFAULT 0,
    must_change_password TINYINT(1) NOT NULL DEFAULT 0,
    last_login_at       DATETIME(6) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at          DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_tenant_email (tenant_id, email),
    UNIQUE KEY uq_user_tenant_username (tenant_id, username),
    CONSTRAINT fk_user_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB;

CREATE TABLE signup_requests (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NULL,
    requested_org_name  VARCHAR(180) NULL,
    full_name           VARCHAR(180) NOT NULL,
    email               VARCHAR(190) NOT NULL,
    phone               VARCHAR(50) NULL,
    password_hash       VARCHAR(255) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING / APPROVED / REJECTED
    requested_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_by_user_id CHAR(36) NULL,
    reviewed_at         DATETIME(6) NULL,
    review_note         VARCHAR(500) NULL,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_signup_status (status, requested_at),
    CONSTRAINT fk_signup_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_signup_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE roles (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(500) NULL,
    is_system       TINYINT(1) NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_role_tenant_name (tenant_id, name),
    CONSTRAINT fk_role_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB;

CREATE TABLE role_modules (
    id              CHAR(36) NOT NULL,
    role_id         CHAR(36) NOT NULL,
    module_id       CHAR(36) NOT NULL,
    is_allowed      TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_role_module (role_id, module_id),
    CONSTRAINT fk_rm_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_rm_module FOREIGN KEY (module_id) REFERENCES platform_modules(id)
) ENGINE=InnoDB;

CREATE TABLE user_roles (
    id              CHAR(36) NOT NULL,
    user_id         CHAR(36) NOT NULL,
    role_id         CHAR(36) NOT NULL,
    site_id         CHAR(36) NULL,
    assigned_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    assigned_by     CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_role_site (user_id, role_id, site_id),
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_ur_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_ur_assigner FOREIGN KEY (assigned_by) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE user_site_access (
    id              CHAR(36) NOT NULL,
    user_id         CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    can_access      TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_site_access (user_id, site_id),
    CONSTRAINT fk_usa_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_usa_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE user_module_access (
    id              CHAR(36) NOT NULL,
    user_id         CHAR(36) NOT NULL,
    site_id         CHAR(36) NULL,
    module_id       CHAR(36) NOT NULL,
    access_mode     VARCHAR(20) NOT NULL DEFAULT 'ALLOW', -- ALLOW / DENY
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_module_access (user_id, site_id, module_id),
    CONSTRAINT fk_uma_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_uma_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_uma_module FOREIGN KEY (module_id) REFERENCES platform_modules(id)
) ENGINE=InnoDB;

CREATE TABLE user_form_permissions (
    id              CHAR(36) NOT NULL,
    user_id         CHAR(36) NOT NULL,
    site_id         CHAR(36) NULL,
    module_key      VARCHAR(80) NOT NULL,
    form_key        VARCHAR(120) NOT NULL,
    can_view        TINYINT(1) NOT NULL DEFAULT 1,
    can_add         TINYINT(1) NOT NULL DEFAULT 0,
    can_edit        TINYINT(1) NOT NULL DEFAULT 0,
    can_delete      TINYINT(1) NOT NULL DEFAULT 0,
    can_approve     TINYINT(1) NOT NULL DEFAULT 0,
    can_export      TINYINT(1) NOT NULL DEFAULT 0,
    can_print       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_form_perm (user_id, site_id, module_key, form_key),
    CONSTRAINT fk_ufp_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ufp_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE site_settings (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    setting_group   VARCHAR(80) NOT NULL,
    setting_key     VARCHAR(120) NOT NULL,
    value_json      JSON NULL,
    is_secret       TINYINT(1) NOT NULL DEFAULT 0,
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_site_setting (site_id, setting_group, setting_key),
    CONSTRAINT fk_ss_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ss_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE document_sequences (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    sequence_key    VARCHAR(80) NOT NULL, -- BILL / PO / GRN / SHIFT / RESERVATION
    business_date   DATE NULL,
    prefix          VARCHAR(30) NULL,
    next_value      BIGINT NOT NULL DEFAULT 1,
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_doc_sequence (site_id, sequence_key, business_date),
    CONSTRAINT fk_ds_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ds_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

-- -----------------------------
-- PRINTER / DEVICE CONFIGURATION
-- -----------------------------

CREATE TABLE printers (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    printer_type    VARCHAR(40) NOT NULL, -- RECEIPT / KITCHEN / BAR / LABEL
    station_code    VARCHAR(80) NULL,
    connection_type VARCHAR(30) NOT NULL DEFAULT 'NETWORK',
    ip_address      VARCHAR(64) NULL,
    port_no         INT NULL,
    windows_name    VARCHAR(255) NULL,
    paper_width_mm  INT NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    is_default      TINYINT(1) NOT NULL DEFAULT 0,
    config_json     JSON NULL,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_printer_site (site_id, printer_type),
    CONSTRAINT fk_printer_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_printer_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE devices (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    device_code     VARCHAR(100) NOT NULL,
    device_name     VARCHAR(160) NOT NULL,
    device_type     VARCHAR(40) NOT NULL, -- POS / TABLET / KDS / RIDER / EDGE
    machine_fingerprint VARCHAR(255) NULL,
    app_version     VARCHAR(60) NULL,
    last_seen_at    DATETIME(6) NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_device_site_code (site_id, device_code),
    CONSTRAINT fk_device_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_device_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

-- -----------------------------
-- MENU / RECIPES
-- -----------------------------

CREATE TABLE menu_categories (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    parent_id       CHAR(36) NULL,
    name            VARCHAR(160) NOT NULL,
    icon_text       VARCHAR(30) NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at      DATETIME(6) NULL,
    row_version     BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id  CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_menu_cat_site (site_id, is_active),
    CONSTRAINT fk_mc_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_mc_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_mc_parent FOREIGN KEY (parent_id) REFERENCES menu_categories(id)
) ENGINE=InnoDB;

CREATE TABLE menu_category_printer_routes (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    category_id     CHAR(36) NOT NULL,
    printer_id      CHAR(36) NOT NULL,
    route_priority  INT NOT NULL DEFAULT 1,
    is_primary      TINYINT(1) NOT NULL DEFAULT 1,
    print_rule      VARCHAR(40) NOT NULL DEFAULT 'PENDING_QTY_ONLY',
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cat_printer_route (category_id, printer_id),
    CONSTRAINT fk_mcpr_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_mcpr_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_mcpr_category FOREIGN KEY (category_id) REFERENCES menu_categories(id),
    CONSTRAINT fk_mcpr_printer FOREIGN KEY (printer_id) REFERENCES printers(id)
) ENGINE=InnoDB;

CREATE TABLE inventory_categories (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at      DATETIME(6) NULL,
    row_version     BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id  CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_inv_cat_site_name (site_id, name),
    CONSTRAINT fk_ic_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ic_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE units (
    id              CHAR(36) NOT NULL,
    code            VARCHAR(30) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    unit_type       VARCHAR(30) NOT NULL, -- WEIGHT / VOLUME / COUNT / PACK
    decimal_places  TINYINT NOT NULL DEFAULT 3,
    PRIMARY KEY (id),
    UNIQUE KEY uq_unit_code (code)
) ENGINE=InnoDB;

CREATE TABLE inventory_items (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    category_id         CHAR(36) NULL,
    sku                 VARCHAR(100) NULL,
    barcode             VARCHAR(120) NULL,
    name                VARCHAR(180) NOT NULL,
    usage_mode          VARCHAR(30) NOT NULL, -- RECIPE_INGREDIENT / DIRECT_SALE / BOTH
    stock_unit_id       CHAR(36) NOT NULL,
    purchase_unit_name  VARCHAR(80) NULL,
    purchase_factor     DECIMAL(18,6) NOT NULL DEFAULT 1,
    avg_cost_per_stock_unit DECIMAL(18,6) NOT NULL DEFAULT 0,
    reorder_level       DECIMAL(18,6) NOT NULL DEFAULT 0,
    track_batch         TINYINT(1) NOT NULL DEFAULT 0,
    track_expiry        TINYINT(1) NOT NULL DEFAULT 0,
    preferred_supplier_id CHAR(36) NULL,
    default_storage_location_id CHAR(36) NULL,
    is_active           TINYINT(1) NOT NULL DEFAULT 1,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at          DATETIME(6) NULL,
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_inv_item_site_sku (site_id, sku),
    KEY ix_inv_item_site_name (site_id, name),
    CONSTRAINT fk_ii_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ii_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_ii_category FOREIGN KEY (category_id) REFERENCES inventory_categories(id),
    CONSTRAINT fk_ii_unit FOREIGN KEY (stock_unit_id) REFERENCES units(id)
) ENGINE=InnoDB;

CREATE TABLE stock_locations (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    code            VARCHAR(80) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    location_type   VARCHAR(40) NOT NULL DEFAULT 'STORE', -- STORE / COLD_ROOM / FREEZER / BAR / KITCHEN
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_loc_site_code (site_id, code),
    CONSTRAINT fk_sl_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sl_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

ALTER TABLE inventory_items
    ADD CONSTRAINT fk_ii_default_location
    FOREIGN KEY (default_storage_location_id) REFERENCES stock_locations(id);

CREATE TABLE menu_items (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    category_id         CHAR(36) NOT NULL,
    code                VARCHAR(100) NULL,
    name                VARCHAR(180) NOT NULL,
    description         VARCHAR(1000) NULL,
    item_type           VARCHAR(30) NOT NULL DEFAULT 'STANDARD', -- STANDARD / WEIGHTED / VARIANT / COMBO
    consumption_type    VARCHAR(30) NOT NULL DEFAULT 'RECIPE', -- RECIPE / DIRECT_INVENTORY / NONE
    direct_inventory_item_id CHAR(36) NULL,
    direct_inventory_qty DECIMAL(18,6) NULL,
    base_price          DECIMAL(18,4) NOT NULL DEFAULT 0,
    image_url           VARCHAR(1000) NULL,
    is_active           TINYINT(1) NOT NULL DEFAULT 1,
    is_online           TINYINT(1) NOT NULL DEFAULT 1,
    is_pos              TINYINT(1) NOT NULL DEFAULT 1,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at          DATETIME(6) NULL,
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_menu_item_site_code (site_id, code),
    KEY ix_menu_item_site_cat (site_id, category_id, is_active),
    CONSTRAINT fk_mi_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_mi_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_mi_category FOREIGN KEY (category_id) REFERENCES menu_categories(id),
    CONSTRAINT fk_mi_direct_inv FOREIGN KEY (direct_inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE menu_item_variants (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    menu_item_id        CHAR(36) NOT NULL,
    code                VARCHAR(100) NULL,
    name                VARCHAR(140) NOT NULL,
    price               DECIMAL(18,4) NOT NULL DEFAULT 0,
    is_default          TINYINT(1) NOT NULL DEFAULT 0,
    is_active           TINYINT(1) NOT NULL DEFAULT 1,
    sort_order          INT NOT NULL DEFAULT 0,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_miv_item (menu_item_id, is_active),
    CONSTRAINT fk_miv_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_miv_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_miv_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id)
) ENGINE=InnoDB;

CREATE TABLE modifier_groups (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    min_select      INT NOT NULL DEFAULT 0,
    max_select      INT NOT NULL DEFAULT 1,
    is_required     TINYINT(1) NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT fk_mg_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_mg_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE modifier_options (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    modifier_group_id   CHAR(36) NOT NULL,
    name                VARCHAR(160) NOT NULL,
    price_delta         DECIMAL(18,4) NOT NULL DEFAULT 0,
    recipe_inventory_item_id CHAR(36) NULL,
    recipe_qty          DECIMAL(18,6) NULL,
    is_active           TINYINT(1) NOT NULL DEFAULT 1,
    sort_order          INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_mo_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_mo_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_mo_group FOREIGN KEY (modifier_group_id) REFERENCES modifier_groups(id),
    CONSTRAINT fk_mo_inv FOREIGN KEY (recipe_inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE menu_item_modifier_groups (
    id                  CHAR(36) NOT NULL,
    menu_item_id        CHAR(36) NOT NULL,
    modifier_group_id   CHAR(36) NOT NULL,
    sort_order          INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_item_modifier_group (menu_item_id, modifier_group_id),
    CONSTRAINT fk_mimg_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id),
    CONSTRAINT fk_mimg_group FOREIGN KEY (modifier_group_id) REFERENCES modifier_groups(id)
) ENGINE=InnoDB;

CREATE TABLE recipes (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    menu_item_id        CHAR(36) NOT NULL,
    variant_id          CHAR(36) NULL,
    version_no          INT NOT NULL DEFAULT 1,
    yield_qty           DECIMAL(18,6) NOT NULL DEFAULT 1,
    preparation_loss_pct DECIMAL(7,4) NOT NULL DEFAULT 0,
    food_cost_amount    DECIMAL(18,4) NOT NULL DEFAULT 0,
    is_current          TINYINT(1) NOT NULL DEFAULT 1,
    effective_from      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    effective_to        DATETIME(6) NULL,
    created_by_user_id  CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_recipe_version (menu_item_id, variant_id, version_no),
    KEY ix_recipe_current (menu_item_id, variant_id, is_current),
    CONSTRAINT fk_recipe_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_recipe_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_recipe_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id),
    CONSTRAINT fk_recipe_variant FOREIGN KEY (variant_id) REFERENCES menu_item_variants(id),
    CONSTRAINT fk_recipe_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE recipe_ingredients (
    id                  CHAR(36) NOT NULL,
    recipe_id           CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    qty_per_yield       DECIMAL(18,6) NOT NULL,
    waste_pct           DECIMAL(7,4) NOT NULL DEFAULT 0,
    line_cost           DECIMAL(18,4) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY ix_ri_recipe (recipe_id),
    CONSTRAINT fk_ri_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id),
    CONSTRAINT fk_ri_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

-- -----------------------------
-- STAFF / TABLES / RESERVATIONS
-- -----------------------------

CREATE TABLE employee_profiles (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    user_id         CHAR(36) NULL,
    employee_no     VARCHAR(80) NULL,
    full_name       VARCHAR(180) NOT NULL,
    job_title       VARCHAR(120) NULL,
    employment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    hire_date       DATE NULL,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_employee_site_no (site_id, employee_no),
    CONSTRAINT fk_ep_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ep_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_ep_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE floors (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    name            VARCHAR(140) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT fk_floor_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_floor_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE dining_tables (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    floor_id        CHAR(36) NULL,
    table_code      VARCHAR(60) NOT NULL,
    display_name    VARCHAR(100) NOT NULL,
    seats           INT NOT NULL DEFAULT 2,
    shape           VARCHAR(30) NOT NULL DEFAULT 'SQUARE',
    position_x      DECIMAL(10,2) NULL,
    position_y      DECIMAL(10,2) NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_table_site_code (site_id, table_code),
    CONSTRAINT fk_dt_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_dt_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_dt_floor FOREIGN KEY (floor_id) REFERENCES floors(id)
) ENGINE=InnoDB;

CREATE TABLE waiter_table_assignments (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    table_id        CHAR(36) NOT NULL,
    employee_id     CHAR(36) NOT NULL,
    shift_date      DATE NOT NULL,
    assigned_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ended_at        DATETIME(6) NULL,
    PRIMARY KEY (id),
    KEY ix_wta_table_date (table_id, shift_date),
    CONSTRAINT fk_wta_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_wta_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_wta_table FOREIGN KEY (table_id) REFERENCES dining_tables(id),
    CONSTRAINT fk_wta_employee FOREIGN KEY (employee_id) REFERENCES employee_profiles(id)
) ENGINE=InnoDB;

-- -----------------------------
-- CUSTOMERS / LOYALTY
-- -----------------------------

CREATE TABLE customers (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NULL,
    customer_no     VARCHAR(80) NULL,
    full_name       VARCHAR(180) NOT NULL,
    phone           VARCHAR(50) NULL,
    email           VARCHAR(190) NULL,
    customer_type   VARCHAR(40) NOT NULL DEFAULT 'REGULAR',
    notes           VARCHAR(1000) NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at      DATETIME(6) NULL,
    row_version     BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id  CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_customer_tenant_phone (tenant_id, phone),
    KEY ix_customer_email (tenant_id, email),
    CONSTRAINT fk_customer_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_customer_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE customer_addresses (
    id              CHAR(36) NOT NULL,
    customer_id     CHAR(36) NOT NULL,
    label           VARCHAR(80) NULL,
    address_text    VARCHAR(500) NOT NULL,
    area            VARCHAR(140) NULL,
    latitude        DECIMAL(10,7) NULL,
    longitude       DECIMAL(10,7) NULL,
    is_default      TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_ca_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
) ENGINE=InnoDB;

CREATE TABLE loyalty_accounts (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    customer_id     CHAR(36) NOT NULL,
    points_balance  DECIMAL(18,2) NOT NULL DEFAULT 0,
    tier_code       VARCHAR(40) NOT NULL DEFAULT 'REGULAR',
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_loyalty_customer (tenant_id, customer_id),
    CONSTRAINT fk_la_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_la_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
) ENGINE=InnoDB;

CREATE TABLE loyalty_transactions (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    customer_id     CHAR(36) NOT NULL,
    site_id         CHAR(36) NULL,
    transaction_type VARCHAR(30) NOT NULL, -- EARN / REDEEM / ADJUST / EXPIRE
    points          DECIMAL(18,2) NOT NULL,
    reference_type  VARCHAR(40) NULL,
    reference_id    CHAR(36) NULL,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_lt_customer (customer_id, created_at),
    CONSTRAINT fk_lt_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_lt_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_lt_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

-- -----------------------------
-- SHIFTS / CASHIER
-- -----------------------------

CREATE TABLE cashier_shifts (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    shift_no            VARCHAR(80) NOT NULL,
    business_date       DATE NOT NULL,
    cashier_user_id     CHAR(36) NOT NULL,
    device_id           CHAR(36) NULL,
    opened_at           DATETIME(6) NOT NULL,
    opening_cash        DECIMAL(18,4) NOT NULL DEFAULT 0,
    closed_at           DATETIME(6) NULL,
    expected_cash       DECIMAL(18,4) NOT NULL DEFAULT 0,
    actual_cash         DECIMAL(18,4) NULL,
    variance_amount     DECIMAL(18,4) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    approved_by_user_id CHAR(36) NULL,
    close_note          VARCHAR(1000) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_shift_site_no (site_id, shift_no),
    KEY ix_shift_date (site_id, business_date, status),
    CONSTRAINT fk_cs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_cs_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_cs_cashier FOREIGN KEY (cashier_user_id) REFERENCES users(id),
    CONSTRAINT fk_cs_device FOREIGN KEY (device_id) REFERENCES devices(id),
    CONSTRAINT fk_cs_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE shift_cash_movements (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    shift_id        CHAR(36) NOT NULL,
    movement_type   VARCHAR(30) NOT NULL, -- CASH_IN / CASH_OUT / EXPENSE
    amount          DECIMAL(18,4) NOT NULL,
    reason          VARCHAR(500) NULL,
    created_by_user_id CHAR(36) NOT NULL,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_scm_shift (shift_id, created_at),
    CONSTRAINT fk_scm_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_scm_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_scm_shift FOREIGN KEY (shift_id) REFERENCES cashier_shifts(id),
    CONSTRAINT fk_scm_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- -----------------------------
-- RESERVATIONS
-- -----------------------------

CREATE TABLE reservations (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    reservation_no  VARCHAR(80) NOT NULL,
    customer_id     CHAR(36) NULL,
    guest_name      VARCHAR(180) NOT NULL,
    guest_phone     VARCHAR(50) NULL,
    reservation_at  DATETIME(6) NOT NULL,
    guest_count     INT NOT NULL DEFAULT 1,
    deposit_amount  DECIMAL(18,4) NOT NULL DEFAULT 0,
    status          VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED',
    notes           VARCHAR(1000) NULL,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_reservation_no (site_id, reservation_no),
    KEY ix_reservation_time (site_id, reservation_at, status),
    CONSTRAINT fk_res_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_res_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_res_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
) ENGINE=InnoDB;

CREATE TABLE reservation_tables (
    id              CHAR(36) NOT NULL,
    reservation_id  CHAR(36) NOT NULL,
    table_id        CHAR(36) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_res_table (reservation_id, table_id),
    CONSTRAINT fk_rt_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_rt_table FOREIGN KEY (table_id) REFERENCES dining_tables(id)
) ENGINE=InnoDB;

-- -----------------------------
-- SALES / ORDERS / KITCHEN
-- -----------------------------

CREATE TABLE orders (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    bill_no             VARCHAR(80) NOT NULL,
    business_date       DATE NOT NULL,
    order_source        VARCHAR(40) NOT NULL DEFAULT 'POS', -- POS / TABLET / CUSTOMER_APP / WEB / QR / MARKETPLACE
    service_mode        VARCHAR(30) NOT NULL, -- DINE_IN / TAKEAWAY / DELIVERY
    order_status        VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    payment_status      VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    table_id            CHAR(36) NULL,
    customer_id         CHAR(36) NULL,
    waiter_user_id      CHAR(36) NULL,
    shift_id            CHAR(36) NULL,
    guest_count         INT NULL,
    subtotal            DECIMAL(18,4) NOT NULL DEFAULT 0,
    discount_amount     DECIMAL(18,4) NOT NULL DEFAULT 0,
    service_charge      DECIMAL(18,4) NOT NULL DEFAULT 0,
    tax_amount          DECIMAL(18,4) NOT NULL DEFAULT 0,
    grand_total         DECIMAL(18,4) NOT NULL DEFAULT 0,
    paid_amount         DECIMAL(18,4) NOT NULL DEFAULT 0,
    change_amount       DECIMAL(18,4) NOT NULL DEFAULT 0,
    hold_status         TINYINT(1) NOT NULL DEFAULT 0,
    held_at             DATETIME(6) NULL,
    opened_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    closed_at           DATETIME(6) NULL,
    created_by_user_id  CHAR(36) NULL,
    device_id           CHAR(36) NULL,
    notes               VARCHAR(1000) NULL,
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_order_site_bill_date (site_id, business_date, bill_no),
    KEY ix_order_site_status (site_id, business_date, order_status),
    KEY ix_order_customer (customer_id, opened_at),
    KEY ix_order_table (table_id, order_status),
    CONSTRAINT fk_order_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_order_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_order_table FOREIGN KEY (table_id) REFERENCES dining_tables(id),
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_order_waiter FOREIGN KEY (waiter_user_id) REFERENCES users(id),
    CONSTRAINT fk_order_shift FOREIGN KEY (shift_id) REFERENCES cashier_shifts(id),
    CONSTRAINT fk_order_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_order_device FOREIGN KEY (device_id) REFERENCES devices(id)
) ENGINE=InnoDB;

CREATE TABLE order_items (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    menu_item_id        CHAR(36) NOT NULL,
    variant_id          CHAR(36) NULL,
    item_name_snapshot  VARCHAR(180) NOT NULL,
    variant_name_snapshot VARCHAR(140) NULL,
    qty                 DECIMAL(18,6) NOT NULL,
    sent_qty            DECIMAL(18,6) NOT NULL DEFAULT 0,
    voided_qty          DECIMAL(18,6) NOT NULL DEFAULT 0,
    unit_price          DECIMAL(18,4) NOT NULL,
    line_discount       DECIMAL(18,4) NOT NULL DEFAULT 0,
    line_tax            DECIMAL(18,4) NOT NULL DEFAULT 0,
    line_total          DECIMAL(18,4) NOT NULL,
    kitchen_note        VARCHAR(500) NULL,
    recipe_id_snapshot  CHAR(36) NULL,
    recipe_version_snapshot INT NULL,
    recipe_snapshot_json JSON NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_order_item_order (order_id),
    CONSTRAINT fk_oi_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_oi_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_oi_menu FOREIGN KEY (menu_item_id) REFERENCES menu_items(id),
    CONSTRAINT fk_oi_variant FOREIGN KEY (variant_id) REFERENCES menu_item_variants(id),
    CONSTRAINT fk_oi_recipe FOREIGN KEY (recipe_id_snapshot) REFERENCES recipes(id)
) ENGINE=InnoDB;

CREATE TABLE order_item_modifiers (
    id                  CHAR(36) NOT NULL,
    order_item_id       CHAR(36) NOT NULL,
    modifier_option_id  CHAR(36) NOT NULL,
    option_name_snapshot VARCHAR(160) NOT NULL,
    qty                 DECIMAL(18,6) NOT NULL DEFAULT 1,
    price_delta         DECIMAL(18,4) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_oim_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id),
    CONSTRAINT fk_oim_option FOREIGN KEY (modifier_option_id) REFERENCES modifier_options(id)
) ENGINE=InnoDB;

CREATE TABLE order_status_history (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    order_id        CHAR(36) NOT NULL,
    from_status     VARCHAR(30) NULL,
    to_status       VARCHAR(30) NOT NULL,
    changed_by_user_id CHAR(36) NULL,
    note            VARCHAR(500) NULL,
    changed_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_osh_order (order_id, changed_at),
    CONSTRAINT fk_osh_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_osh_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_osh_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_osh_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE kitchen_tickets (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    ticket_no           VARCHAR(80) NOT NULL,
    printer_id          CHAR(36) NULL,
    station_code        VARCHAR(80) NULL,
    ticket_status       VARCHAR(30) NOT NULL DEFAULT 'NEW',
    sent_at             DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at          DATETIME(6) NULL,
    ready_at            DATETIME(6) NULL,
    completed_at        DATETIME(6) NULL,
    reprint_count       INT NOT NULL DEFAULT 0,
    created_by_user_id  CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_kt_order (order_id, sent_at),
    KEY ix_kt_station_status (site_id, station_code, ticket_status),
    CONSTRAINT fk_kt_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_kt_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_kt_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_kt_printer FOREIGN KEY (printer_id) REFERENCES printers(id),
    CONSTRAINT fk_kt_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE kitchen_ticket_items (
    id                  CHAR(36) NOT NULL,
    kitchen_ticket_id   CHAR(36) NOT NULL,
    order_item_id       CHAR(36) NOT NULL,
    qty_sent            DECIMAL(18,6) NOT NULL,
    item_status         VARCHAR(30) NOT NULL DEFAULT 'NEW',
    note_snapshot       VARCHAR(500) NULL,
    started_at          DATETIME(6) NULL,
    ready_at            DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_kti_ticket FOREIGN KEY (kitchen_ticket_id) REFERENCES kitchen_tickets(id),
    CONSTRAINT fk_kti_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
) ENGINE=InnoDB;

CREATE TABLE order_item_voids (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    order_item_id       CHAR(36) NOT NULL,
    void_qty            DECIMAL(18,6) NOT NULL,
    reason_code         VARCHAR(80) NOT NULL,
    reason_note         VARCHAR(1000) NULL,
    requested_by_user_id CHAR(36) NOT NULL,
    approved_by_user_id CHAR(36) NULL,
    approval_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    approved_at         DATETIME(6) NULL,
    PRIMARY KEY (id),
    KEY ix_oiv_order (order_id, created_at),
    CONSTRAINT fk_oiv_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_oiv_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_oiv_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_oiv_item FOREIGN KEY (order_item_id) REFERENCES order_items(id),
    CONSTRAINT fk_oiv_requester FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_oiv_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- -----------------------------
-- PAYMENT / TAX / PROMOTIONS
-- -----------------------------

CREATE TABLE payment_methods (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    code            VARCHAR(50) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    method_type     VARCHAR(30) NOT NULL, -- CASH / CARD / BANK / WALLET / COD
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    config_json     JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_payment_method_site_code (site_id, code),
    CONSTRAINT fk_pm_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_pm_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE tax_profiles (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    name            VARCHAR(120) NOT NULL,
    tax_percent     DECIMAL(7,4) NOT NULL DEFAULT 0,
    payment_method_id CHAR(36) NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT fk_tax_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_tax_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_tax_payment FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id)
) ENGINE=InnoDB;

CREATE TABLE payments (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    shift_id            CHAR(36) NULL,
    payment_method_id   CHAR(36) NOT NULL,
    amount              DECIMAL(18,4) NOT NULL,
    received_amount     DECIMAL(18,4) NULL,
    change_amount       DECIMAL(18,4) NOT NULL DEFAULT 0,
    provider_reference  VARCHAR(255) NULL,
    provider_fee        DECIMAL(18,4) NOT NULL DEFAULT 0,
    application_fee     DECIMAL(18,4) NOT NULL DEFAULT 0,
    status              VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    paid_at             DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_user_id  CHAR(36) NULL,
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_payment_order (order_id, paid_at),
    KEY ix_payment_shift (shift_id, paid_at),
    CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_payment_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_payment_shift FOREIGN KEY (shift_id) REFERENCES cashier_shifts(id),
    CONSTRAINT fk_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id),
    CONSTRAINT fk_payment_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE refunds (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    payment_id          CHAR(36) NULL,
    refund_amount       DECIMAL(18,4) NOT NULL,
    reason_code         VARCHAR(80) NOT NULL,
    reason_note         VARCHAR(1000) NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    requested_by_user_id CHAR(36) NOT NULL,
    approved_by_user_id CHAR(36) NULL,
    provider_reference  VARCHAR(255) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    approved_at         DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_ref_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ref_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_ref_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_ref_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
    CONSTRAINT fk_ref_requester FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_ref_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE promotions (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NOT NULL,
    name            VARCHAR(180) NOT NULL,
    promotion_type  VARCHAR(40) NOT NULL, -- PERCENT / FIXED / BOGO / COMBO / COUPON
    code            VARCHAR(80) NULL,
    starts_at       DATETIME(6) NULL,
    ends_at         DATETIME(6) NULL,
    rules_json      JSON NOT NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_promo_site_active (site_id, is_active, starts_at, ends_at),
    CONSTRAINT fk_promo_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_promo_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE order_promotions (
    id              CHAR(36) NOT NULL,
    order_id        CHAR(36) NOT NULL,
    promotion_id    CHAR(36) NULL,
    description     VARCHAR(255) NULL,
    discount_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_op_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_op_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id)
) ENGINE=InnoDB;

-- -----------------------------
-- SUPPLIERS / PURCHASING
-- -----------------------------

CREATE TABLE suppliers (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    site_id         CHAR(36) NULL,
    supplier_code   VARCHAR(80) NULL,
    name            VARCHAR(180) NOT NULL,
    contact_person  VARCHAR(160) NULL,
    phone           VARCHAR(50) NULL,
    email           VARCHAR(190) NULL,
    address_text    VARCHAR(500) NULL,
    tax_no          VARCHAR(80) NULL,
    credit_days     INT NOT NULL DEFAULT 0,
    opening_balance DECIMAL(18,4) NOT NULL DEFAULT 0,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_supplier_tenant_name (tenant_id, name),
    CONSTRAINT fk_supplier_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_supplier_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

ALTER TABLE inventory_items
    ADD CONSTRAINT fk_ii_supplier
    FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers(id);

CREATE TABLE supplier_items (
    id                  CHAR(36) NOT NULL,
    supplier_id         CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    supplier_sku        VARCHAR(100) NULL,
    last_purchase_cost  DECIMAL(18,4) NOT NULL DEFAULT 0,
    is_preferred        TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_supplier_item (supplier_id, inventory_item_id),
    CONSTRAINT fk_si_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_si_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE purchase_orders (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    po_no               VARCHAR(80) NOT NULL,
    supplier_id         CHAR(36) NOT NULL,
    order_date          DATE NOT NULL,
    expected_date       DATE NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    subtotal            DECIMAL(18,4) NOT NULL DEFAULT 0,
    discount_amount     DECIMAL(18,4) NOT NULL DEFAULT 0,
    tax_amount          DECIMAL(18,4) NOT NULL DEFAULT 0,
    total_amount        DECIMAL(18,4) NOT NULL DEFAULT 0,
    notes               VARCHAR(1000) NULL,
    created_by_user_id  CHAR(36) NULL,
    approved_by_user_id CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_po_site_no (site_id, po_no),
    KEY ix_po_supplier (supplier_id, order_date),
    CONSTRAINT fk_po_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_po_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_po_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_po_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE purchase_order_items (
    id                  CHAR(36) NOT NULL,
    purchase_order_id   CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    purchase_qty        DECIMAL(18,6) NOT NULL,
    purchase_unit_name  VARCHAR(80) NOT NULL,
    purchase_factor     DECIMAL(18,6) NOT NULL DEFAULT 1,
    unit_cost           DECIMAL(18,4) NOT NULL,
    tax_amount          DECIMAL(18,4) NOT NULL DEFAULT 0,
    line_total          DECIMAL(18,4) NOT NULL,
    received_qty        DECIMAL(18,6) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY ix_poi_po (purchase_order_id),
    CONSTRAINT fk_poi_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_poi_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE goods_receipts (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    grn_no              VARCHAR(80) NOT NULL,
    purchase_order_id   CHAR(36) NULL,
    supplier_id         CHAR(36) NOT NULL,
    supplier_invoice_no VARCHAR(120) NULL,
    received_at         DATETIME(6) NOT NULL,
    total_amount        DECIMAL(18,4) NOT NULL DEFAULT 0,
    status              VARCHAR(30) NOT NULL DEFAULT 'POSTED',
    received_by_user_id CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_grn_site_no (site_id, grn_no),
    CONSTRAINT fk_gr_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_gr_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_gr_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_gr_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_gr_user FOREIGN KEY (received_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE goods_receipt_items (
    id                  CHAR(36) NOT NULL,
    goods_receipt_id    CHAR(36) NOT NULL,
    purchase_order_item_id CHAR(36) NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    purchase_qty        DECIMAL(18,6) NOT NULL,
    purchase_factor     DECIMAL(18,6) NOT NULL,
    stock_qty_received  DECIMAL(18,6) NOT NULL,
    unit_cost           DECIMAL(18,4) NOT NULL,
    batch_no            VARCHAR(120) NULL,
    expiry_date         DATE NULL,
    line_total          DECIMAL(18,4) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_gri_gr FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(id),
    CONSTRAINT fk_gri_poi FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_items(id),
    CONSTRAINT fk_gri_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE supplier_payments (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    supplier_id         CHAR(36) NOT NULL,
    payment_date        DATE NOT NULL,
    amount              DECIMAL(18,4) NOT NULL,
    payment_method      VARCHAR(40) NOT NULL,
    reference_no        VARCHAR(150) NULL,
    notes               VARCHAR(500) NULL,
    created_by_user_id  CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_sp_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sp_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_sp_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_sp_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- -----------------------------
-- INVENTORY BALANCES / MOVEMENTS
-- -----------------------------

CREATE TABLE stock_balances (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    stock_location_id   CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    qty_on_hand         DECIMAL(18,6) NOT NULL DEFAULT 0,
    avg_cost            DECIMAL(18,6) NOT NULL DEFAULT 0,
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_balance (stock_location_id, inventory_item_id),
    KEY ix_sb_site_item (site_id, inventory_item_id),
    CONSTRAINT fk_sb_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sb_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_sb_location FOREIGN KEY (stock_location_id) REFERENCES stock_locations(id),
    CONSTRAINT fk_sb_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE stock_batches (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    stock_location_id   CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    batch_no            VARCHAR(120) NOT NULL,
    expiry_date         DATE NULL,
    qty_on_hand         DECIMAL(18,6) NOT NULL DEFAULT 0,
    unit_cost           DECIMAL(18,6) NOT NULL DEFAULT 0,
    received_at         DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_batch_item_loc (stock_location_id, inventory_item_id, batch_no),
    KEY ix_batch_expiry (site_id, expiry_date),
    CONSTRAINT fk_batch_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_batch_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_batch_location FOREIGN KEY (stock_location_id) REFERENCES stock_locations(id),
    CONSTRAINT fk_batch_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE stock_transactions (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    transaction_type    VARCHAR(40) NOT NULL, -- OPENING / PURCHASE / SALE / WASTAGE / ADJUSTMENT / TRANSFER_OUT / TRANSFER_IN / RETURN
    business_date       DATE NOT NULL,
    reference_type      VARCHAR(40) NULL,
    reference_id        CHAR(36) NULL,
    reference_no        VARCHAR(100) NULL,
    reason_code         VARCHAR(80) NULL,
    notes               VARCHAR(1000) NULL,
    posted_by_user_id   CHAR(36) NULL,
    posted_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
    origin_node_id      CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_st_site_date (site_id, business_date, transaction_type),
    KEY ix_st_reference (reference_type, reference_id),
    CONSTRAINT fk_st_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_st_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_st_user FOREIGN KEY (posted_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE stock_transaction_lines (
    id                  CHAR(36) NOT NULL,
    stock_transaction_id CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    stock_location_id   CHAR(36) NOT NULL,
    batch_id            CHAR(36) NULL,
    qty_change          DECIMAL(18,6) NOT NULL, -- signed: + receive, - consume
    unit_cost           DECIMAL(18,6) NOT NULL DEFAULT 0,
    value_change        DECIMAL(18,4) NOT NULL DEFAULT 0,
    source_order_item_id CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_stl_item (inventory_item_id),
    CONSTRAINT fk_stl_tx FOREIGN KEY (stock_transaction_id) REFERENCES stock_transactions(id),
    CONSTRAINT fk_stl_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT fk_stl_location FOREIGN KEY (stock_location_id) REFERENCES stock_locations(id),
    CONSTRAINT fk_stl_batch FOREIGN KEY (batch_id) REFERENCES stock_batches(id),
    CONSTRAINT fk_stl_order_item FOREIGN KEY (source_order_item_id) REFERENCES order_items(id)
) ENGINE=InnoDB;

CREATE TABLE stock_adjustments (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    adjustment_no       VARCHAR(80) NOT NULL,
    reason_code         VARCHAR(80) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_by_user_id CHAR(36) NOT NULL,
    approved_by_user_id CHAR(36) NULL,
    requested_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    approved_at         DATETIME(6) NULL,
    note                VARCHAR(1000) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_adjust_site_no (site_id, adjustment_no),
    CONSTRAINT fk_sa_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sa_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_sa_req FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_sa_app FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE stock_adjustment_items (
    id                  CHAR(36) NOT NULL,
    adjustment_id       CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    stock_location_id   CHAR(36) NOT NULL,
    qty_change          DECIMAL(18,6) NOT NULL,
    note                VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_sai_adjust FOREIGN KEY (adjustment_id) REFERENCES stock_adjustments(id),
    CONSTRAINT fk_sai_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT fk_sai_loc FOREIGN KEY (stock_location_id) REFERENCES stock_locations(id)
) ENGINE=InnoDB;

CREATE TABLE stock_count_sessions (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    count_no            VARCHAR(80) NOT NULL,
    stock_location_id   CHAR(36) NULL,
    started_at          DATETIME(6) NOT NULL,
    completed_at        DATETIME(6) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    started_by_user_id  CHAR(36) NOT NULL,
    approved_by_user_id CHAR(36) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_count_site_no (site_id, count_no),
    CONSTRAINT fk_scs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_scs_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_scs_loc FOREIGN KEY (stock_location_id) REFERENCES stock_locations(id),
    CONSTRAINT fk_scs_user FOREIGN KEY (started_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_scs_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE stock_count_items (
    id                  CHAR(36) NOT NULL,
    count_session_id    CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    system_qty          DECIMAL(18,6) NOT NULL,
    physical_qty        DECIMAL(18,6) NULL,
    variance_qty        DECIMAL(18,6) NULL,
    variance_value      DECIMAL(18,4) NULL,
    reason_code         VARCHAR(80) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_count_item (count_session_id, inventory_item_id),
    CONSTRAINT fk_sci_session FOREIGN KEY (count_session_id) REFERENCES stock_count_sessions(id),
    CONSTRAINT fk_sci_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

CREATE TABLE stock_transfers (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    from_site_id        CHAR(36) NOT NULL,
    to_site_id          CHAR(36) NOT NULL,
    transfer_no         VARCHAR(80) NOT NULL,
    transfer_date       DATE NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
    requested_by_user_id CHAR(36) NULL,
    approved_by_user_id CHAR(36) NULL,
    dispatched_at       DATETIME(6) NULL,
    received_at         DATETIME(6) NULL,
    notes               VARCHAR(1000) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_transfer_from_no (from_site_id, transfer_no),
    CONSTRAINT fk_transfer_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_transfer_from FOREIGN KEY (from_site_id) REFERENCES sites(id),
    CONSTRAINT fk_transfer_to FOREIGN KEY (to_site_id) REFERENCES sites(id),
    CONSTRAINT fk_transfer_req FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_transfer_app FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE stock_transfer_items (
    id                  CHAR(36) NOT NULL,
    transfer_id         CHAR(36) NOT NULL,
    inventory_item_id   CHAR(36) NOT NULL,
    requested_qty       DECIMAL(18,6) NOT NULL,
    dispatched_qty      DECIMAL(18,6) NULL,
    received_qty        DECIMAL(18,6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_sti_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers(id),
    CONSTRAINT fk_sti_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB;

-- -----------------------------
-- ONLINE ORDER / DELIVERY / RIDERS
-- -----------------------------

CREATE TABLE online_order_details (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    channel_code        VARCHAR(60) NOT NULL, -- APP / WEB / QR / FOODPANDA...
    external_order_no   VARCHAR(120) NULL,
    acceptance_status   VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    requested_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    accepted_at         DATETIME(6) NULL,
    rejected_at         DATETIME(6) NULL,
    rejection_reason    VARCHAR(500) NULL,
    raw_payload_json    JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_online_order (order_id),
    KEY ix_online_pending (site_id, acceptance_status, requested_at),
    CONSTRAINT fk_ood_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ood_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_ood_order FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB;

CREATE TABLE riders (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    employee_id         CHAR(36) NULL,
    name                VARCHAR(180) NOT NULL,
    phone               VARCHAR(50) NULL,
    vehicle_no          VARCHAR(80) NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    cash_held           DECIMAL(18,4) NOT NULL DEFAULT 0,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_rider_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_rider_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_rider_employee FOREIGN KEY (employee_id) REFERENCES employee_profiles(id)
) ENGINE=InnoDB;

CREATE TABLE delivery_orders (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    customer_address_id CHAR(36) NULL,
    address_snapshot    VARCHAR(500) NOT NULL,
    delivery_area       VARCHAR(140) NULL,
    delivery_fee        DECIMAL(18,4) NOT NULL DEFAULT 0,
    rider_id            CHAR(36) NULL,
    delivery_status     VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    assigned_at         DATETIME(6) NULL,
    picked_up_at        DATETIME(6) NULL,
    delivered_at        DATETIME(6) NULL,
    cod_amount          DECIMAL(18,4) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_delivery_order (order_id),
    KEY ix_delivery_status (site_id, delivery_status),
    CONSTRAINT fk_do_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_do_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_do_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_do_address FOREIGN KEY (customer_address_id) REFERENCES customer_addresses(id),
    CONSTRAINT fk_do_rider FOREIGN KEY (rider_id) REFERENCES riders(id)
) ENGINE=InnoDB;

CREATE TABLE rider_settlements (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    rider_id            CHAR(36) NOT NULL,
    settlement_date     DATE NOT NULL,
    expected_cod        DECIMAL(18,4) NOT NULL DEFAULT 0,
    cash_received       DECIMAL(18,4) NOT NULL DEFAULT 0,
    variance_amount     DECIMAL(18,4) NOT NULL DEFAULT 0,
    settled_by_user_id  CHAR(36) NOT NULL,
    settled_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_rs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_rs_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_rs_rider FOREIGN KEY (rider_id) REFERENCES riders(id),
    CONSTRAINT fk_rs_user FOREIGN KEY (settled_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- -----------------------------
-- EXPENSES / ACCOUNTING
-- -----------------------------

CREATE TABLE expense_categories (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    name            VARCHAR(160) NOT NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_exp_cat_tenant_name (tenant_id, name),
    CONSTRAINT fk_ec_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB;

CREATE TABLE expenses (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    expense_no          VARCHAR(80) NOT NULL,
    expense_date        DATE NOT NULL,
    category_id         CHAR(36) NOT NULL,
    amount              DECIMAL(18,4) NOT NULL,
    payment_method      VARCHAR(40) NOT NULL,
    shift_id            CHAR(36) NULL,
    description         VARCHAR(1000) NULL,
    attachment_url      VARCHAR(1000) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    created_by_user_id  CHAR(36) NOT NULL,
    approved_by_user_id CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_expense_site_no (site_id, expense_no),
    KEY ix_expense_date (site_id, expense_date),
    CONSTRAINT fk_exp_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_exp_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_exp_category FOREIGN KEY (category_id) REFERENCES expense_categories(id),
    CONSTRAINT fk_exp_shift FOREIGN KEY (shift_id) REFERENCES cashier_shifts(id),
    CONSTRAINT fk_exp_user FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_exp_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE accounts (
    id              CHAR(36) NOT NULL,
    tenant_id       CHAR(36) NOT NULL,
    code            VARCHAR(60) NOT NULL,
    name            VARCHAR(180) NOT NULL,
    account_type    VARCHAR(30) NOT NULL, -- ASSET / LIABILITY / EQUITY / REVENUE / EXPENSE
    parent_id       CHAR(36) NULL,
    is_control      TINYINT(1) NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_account_tenant_code (tenant_id, code),
    CONSTRAINT fk_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_account_parent FOREIGN KEY (parent_id) REFERENCES accounts(id)
) ENGINE=InnoDB;

CREATE TABLE journal_entries (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    journal_no          VARCHAR(80) NOT NULL,
    journal_date        DATE NOT NULL,
    reference_type      VARCHAR(40) NULL,
    reference_id        CHAR(36) NULL,
    narration           VARCHAR(1000) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'POSTED',
    created_by_user_id  CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_journal_tenant_no (tenant_id, journal_no),
    KEY ix_je_date (tenant_id, journal_date),
    CONSTRAINT fk_je_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_je_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_je_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE journal_lines (
    id              CHAR(36) NOT NULL,
    journal_entry_id CHAR(36) NOT NULL,
    account_id      CHAR(36) NOT NULL,
    debit_amount    DECIMAL(18,4) NOT NULL DEFAULT 0,
    credit_amount   DECIMAL(18,4) NOT NULL DEFAULT 0,
    memo            VARCHAR(500) NULL,
    PRIMARY KEY (id),
    KEY ix_jl_entry (journal_entry_id),
    CONSTRAINT fk_jl_entry FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id),
    CONSTRAINT fk_jl_account FOREIGN KEY (account_id) REFERENCES accounts(id)
) ENGINE=InnoDB;

-- -----------------------------
-- FBR / NOTIFICATIONS
-- -----------------------------

CREATE TABLE fiscal_settings (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    provider_code       VARCHAR(40) NOT NULL DEFAULT 'FBR',
    environment         VARCHAR(20) NOT NULL DEFAULT 'SANDBOX',
    is_enabled          TINYINT(1) NOT NULL DEFAULT 0,
    pos_id              VARCHAR(120) NULL,
    config_encrypted    MEDIUMBLOB NULL,
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_fiscal_site_provider (site_id, provider_code),
    CONSTRAINT fk_fs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fs_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE fiscal_invoices (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    order_id            CHAR(36) NOT NULL,
    provider_code       VARCHAR(40) NOT NULL DEFAULT 'FBR',
    provider_invoice_no VARCHAR(180) NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    qr_payload          LONGTEXT NULL,
    request_json        JSON NULL,
    response_json       JSON NULL,
    submitted_at        DATETIME(6) NULL,
    verified_at         DATETIME(6) NULL,
    retry_count         INT NOT NULL DEFAULT 0,
    last_error          TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fiscal_order_provider (order_id, provider_code),
    KEY ix_fiscal_pending (site_id, status),
    CONSTRAINT fk_fi_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fi_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_fi_order FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB;

CREATE TABLE notification_queue (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    channel             VARCHAR(30) NOT NULL, -- WHATSAPP / PUSH / SMS / EMAIL
    recipient           VARCHAR(255) NOT NULL,
    template_key        VARCHAR(100) NULL,
    payload_json        JSON NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempts            INT NOT NULL DEFAULT 0,
    available_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    sent_at             DATETIME(6) NULL,
    last_error          TEXT NULL,
    idempotency_key     VARCHAR(160) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_notification_idempotency (idempotency_key),
    KEY ix_notification_pending (status, available_at),
    CONSTRAINT fk_nq_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_nq_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE printer_jobs (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NOT NULL,
    printer_id          CHAR(36) NOT NULL,
    job_type            VARCHAR(40) NOT NULL, -- KOT / RECEIPT / DUPLICATE / LABEL
    reference_type      VARCHAR(40) NULL,
    reference_id        CHAR(36) NULL,
    payload_text        LONGTEXT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempts            INT NOT NULL DEFAULT 0,
    queued_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    printed_at          DATETIME(6) NULL,
    last_error          TEXT NULL,
    PRIMARY KEY (id),
    KEY ix_print_pending (site_id, status, queued_at),
    CONSTRAINT fk_pj_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_pj_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_pj_printer FOREIGN KEY (printer_id) REFERENCES printers(id)
) ENGINE=InnoDB;

-- -----------------------------
-- AUDIT + OFFLINE SYNC
-- -----------------------------

CREATE TABLE audit_logs (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    user_id             CHAR(36) NULL,
    action_code         VARCHAR(100) NOT NULL,
    entity_type         VARCHAR(100) NULL,
    entity_id           CHAR(36) NULL,
    old_values_json     JSON NULL,
    new_values_json     JSON NULL,
    device_id           CHAR(36) NULL,
    ip_address          VARCHAR(64) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_audit_entity (tenant_id, entity_type, entity_id),
    KEY ix_audit_user_time (user_id, created_at),
    CONSTRAINT fk_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_audit_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_device FOREIGN KEY (device_id) REFERENCES devices(id)
) ENGINE=InnoDB;

CREATE TABLE sync_nodes (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    node_type           VARCHAR(30) NOT NULL, -- CLOUD / EDGE
    node_code           VARCHAR(100) NOT NULL,
    machine_fingerprint VARCHAR(255) NULL,
    last_seen_at        DATETIME(6) NULL,
    app_version         VARCHAR(60) NULL,
    schema_version      VARCHAR(60) NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_node_code (tenant_id, node_code),
    CONSTRAINT fk_sn_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sn_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

CREATE TABLE sync_outbox (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    source_node_id      CHAR(36) NOT NULL,
    entity_table        VARCHAR(120) NOT NULL,
    entity_id           CHAR(36) NOT NULL,
    operation_type      VARCHAR(20) NOT NULL, -- INSERT / UPDATE / DELETE / EVENT
    row_version         BIGINT UNSIGNED NULL,
    payload_json        JSON NOT NULL,
    idempotency_key     VARCHAR(180) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts            INT NOT NULL DEFAULT 0,
    next_attempt_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    sent_at             DATETIME(6) NULL,
    last_error          TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_outbox_idem (idempotency_key),
    KEY ix_sync_outbox_pending (status, next_attempt_at),
    CONSTRAINT fk_so_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_so_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_so_node FOREIGN KEY (source_node_id) REFERENCES sync_nodes(id)
) ENGINE=InnoDB;

CREATE TABLE sync_inbox (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    source_node_id      CHAR(36) NOT NULL,
    idempotency_key     VARCHAR(180) NOT NULL,
    entity_table        VARCHAR(120) NOT NULL,
    entity_id           CHAR(36) NOT NULL,
    processed_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    result_status       VARCHAR(20) NOT NULL DEFAULT 'APPLIED',
    error_text          TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_inbox_idem (idempotency_key),
    CONSTRAINT fk_si_tenant2 FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_si_site2 FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_si_node2 FOREIGN KEY (source_node_id) REFERENCES sync_nodes(id)
) ENGINE=InnoDB;

CREATE TABLE sync_cursors (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    node_id             CHAR(36) NOT NULL,
    stream_key          VARCHAR(100) NOT NULL,
    cursor_value        VARCHAR(255) NULL,
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_cursor (node_id, stream_key),
    CONSTRAINT fk_sc_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sc_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_sc_node FOREIGN KEY (node_id) REFERENCES sync_nodes(id)
) ENGINE=InnoDB;

CREATE TABLE sync_conflicts (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    entity_table        VARCHAR(120) NOT NULL,
    entity_id           CHAR(36) NOT NULL,
    local_version       BIGINT UNSIGNED NULL,
    cloud_version       BIGINT UNSIGNED NULL,
    local_payload_json  JSON NULL,
    cloud_payload_json  JSON NULL,
    conflict_reason     VARCHAR(255) NULL,
    resolution_status   VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    resolved_by_user_id CHAR(36) NULL,
    resolved_at         DATETIME(6) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY ix_sync_conflict_pending (tenant_id, resolution_status),
    CONSTRAINT fk_scf_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_scf_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_scf_user FOREIGN KEY (resolved_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE background_jobs (
    id                  CHAR(36) NOT NULL,
    tenant_id           CHAR(36) NOT NULL,
    site_id             CHAR(36) NULL,
    job_type            VARCHAR(80) NOT NULL, -- SYNC / FBR / WHATSAPP / PRINT / BACKUP
    reference_id        CHAR(36) NULL,
    payload_json        JSON NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts            INT NOT NULL DEFAULT 0,
    available_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_at           DATETIME(6) NULL,
    completed_at        DATETIME(6) NULL,
    last_error          TEXT NULL,
    PRIMARY KEY (id),
    KEY ix_bg_pending (status, available_at),
    CONSTRAINT fk_bg_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_bg_site FOREIGN KEY (site_id) REFERENCES sites(id)
) ENGINE=InnoDB;

INSERT INTO schema_migrations(version, description)
VALUES ('V1', 'All-in-one platform core + Restaurant operational schema');

-- Cloud-only commercial tables intentionally omitted from local DB.

-- build: V17.1 build 2026-08-25
